// Localization dictionary
const translations = {
  en: {
    // Onboarding Screen
    'justifi': 'JustiFi',
    'instant_micro_loans': 'Instant Micro-Loans Using Receipts',
    'get_approved': 'Get approved in minutes without CIBIL or PAN',
    'decision_time': 'Decision in under 5 minutes',
    'no_pan_required': 'No PAN/Aadhaar required',
    'loan_amount': 'Loans up to ₹10,000',
    'get_started': 'Get Started',
    'terms_consent': 'By continuing, you agree to our Terms of Service and Privacy Policy',
    
    // Upload Screen
    'upload_documents': 'Upload Documents',
    'upload_salary_receipt': 'Upload Salary Receipt',
    'upload_salary_receipt_description': 'Please upload your latest salary receipt for credit assessment',
    'choose_salary_receipt': 'Choose Salary Receipt',
    'upload_salary_receipt_button': 'Upload Salary Receipt',
    'upload_bank_statement': 'Upload Bank Statement',
    'upload_bank_statement_description': 'Please upload your recent bank statement for credit assessment',
    'choose_bank_statement': 'Choose Bank Statement',
    'upload_bank_statement_button': 'Upload Bank Statement',
    'or_try_demo': 'Or try with demo data',
    'select_demo_user': 'Select Demo User',
    'please_select_demo_user': 'Please select a demo user',
    'calculate_my_score': 'Calculate My Score',
    'processing': 'Processing...',
    'please_upload_both_documents': 'Please upload both salary receipt and bank statement',
    'salary_receipt_uploaded_successfully': 'Salary receipt uploaded successfully',
    'bank_statement_uploaded_successfully': 'Bank statement uploaded successfully',
    'please_select_file': 'Please select a file to upload',
    'please_upload_at_least_one_document': 'Please upload at least one document or select a demo user',
    'error_processing_request': 'Error processing request',
    'no_pan_aadhaar_required': 'No PAN or Aadhaar required. We protect your privacy.',
    'restart_upload': 'Upload Different Documents',

    // Result Screen
    'your_credit_assessment': 'Your Credit Assessment',
    'trust_score': 'TrustScore',
    'top_reasons': 'Top Reasons',
    'loan_offer': 'Loan Offer',
    'available_for_disbursement': 'Available for immediate disbursement',
    'accept_loan': 'Accept Loan',
    'loan_disbursed_success': 'Loan of ₹{amount} has been successfully disbursed!',
    'failed_to_disburse_loan': 'Failed to disburse loan',
    'loan_approved': 'Loan Approved!',
    'error': 'Error',
    'transaction_id': 'Transaction ID',
    'amount': 'Amount',
    'view_profile': 'View Profile',
    'loan_history': 'Loan History',
    'spending_patterns': 'Spending Patterns',
    'settings': 'Settings',
    'assess_another_person': 'Assess Another Person',
    'data_protected': 'Your data is protected. We only use it for credit assessment.',
    'approved': 'Approved',
    'approved_with_cap': 'Approved with Cap',
    'under_review': 'Under Review',
    'rejected': 'Rejected',
    'pending': 'Pending',
    'loading': 'Loading',
    'hundred': '100',
    
    // Profile Screen
    'user_profile': 'User Profile',
    'user': 'User',
    'user_initial': 'U',
    'email': 'Email',
    'phone': 'Phone',
    'address': 'Address',
    'occupation': 'Occupation',
    'not_provided': 'Not provided',
    'edit_profile': 'Edit Profile',
    'upload_document': 'Upload Document',
    'view_notifications': 'Notifications',
    'view_loan_history': 'View Loan History',
    'view_spending_patterns': 'View Spending Patterns',
    'app_settings': 'App Settings',
    'logout': 'Logout',
    'mark_all_as_read': 'Mark All as Read',
    'no_notifications': 'No notifications',
    'unread': 'Unread',
    'full_name': 'Full Name',
    'enter_full_name': 'Enter your full name',
    'enter_email': 'Enter your email',
    'enter_phone_number': 'Enter your phone number',
    'enter_address': 'Enter your address',
    'enter_occupation': 'Enter your occupation',
    'cancel': 'Cancel',
    'save_changes': 'Save Changes',
    'back': 'Back',
    'notifications_feature_coming_soon': 'Notifications feature is coming soon!',
    
    // Loan History Screen
    'loading_loan_history': 'Loading loan history',
    'no_loan_history_found': 'No loan history found',
    'disbursed': 'Disbursed',
    'repaid': 'Repaid',
    'repayment_due': 'Repayment Due',
    
    // Spending Patterns Screen
    'spending_patterns_title': 'Spending Patterns',
    'loading_spending_patterns': 'Loading spending patterns',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'spending_by_category': 'Spending by Category',
    'spending_summary': 'Spending Summary',
    'groceries': 'Groceries',
    'transport': 'Transport',
    'entertainment': 'Entertainment',
    'utilities': 'Utilities',
    'dining': 'Dining',
    'other': 'Other',
    'rent': 'Rent',
    'user_diary': 'User Diary',
    'add_financial_note': 'Add a financial note or activity...',
    'add_entry': 'Add Entry',
    'delete': 'Delete',
    'no_diary_entries': 'No diary entries yet. Add your first financial note!',
    
    // Settings Screen
    'notifications': 'Notifications',
    'enable_notifications': 'Enable Notifications',
    'email_notifications': 'Email Notifications',
    'sms_notifications': 'SMS Notifications',
    'appearance': 'Appearance',
    'dark_mode': 'Dark Mode',
    'view_mode': 'View Mode',
    'mobile_view': 'Mobile View',
    'desktop_view': 'Desktop View',
    'preferences': 'Preferences',
    'language': 'Language',
    'currency': 'Currency',
    'english': 'English',
    'hindi': 'Hindi',
    'tamil': 'Tamil',
    'telugu': 'Telugu',
    'kannada': 'Kannada',
    'indian_rupee': 'Indian Rupee (₹)',
    'us_dollar': 'US Dollar ($)',
    'euro': 'Euro (€)',
    'reset_to_default': 'Reset to Default',
    'save_settings': 'Save Settings',
    'settings_saved_successfully': 'Settings saved successfully!',
    
    // Login/Signup
    'login': 'Login',
    'signup': 'Sign Up',
    'email_or_username': 'Email or Username',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'processing': 'Processing...',
    'passwords_do_not_match': 'Passwords do not match',
    'password_min_length': 'Password must be at least 6 characters long',
    'email_gmail_required': 'Email must be a valid Gmail address ending with @gmail.com',
    'select_your_role': 'Select Your Role',
    'signup_as_user': 'Signup as User',
    'user_role_description': 'Apply for micro-loans using receipt data',
    'signup_as_banker': 'Signup as Banker',
    'banker_role_description': 'Review loan applications and manage users',
    'signup_as_admin': 'Signup as Admin',
    'admin_role_description': 'Manage the platform and user accounts',
    'select_role_to_continue': 'Select Role to Continue',
    'no_role_selected': 'No role selected',
    'selected_role': 'Selected Role',
    'change': 'Change',
    'user': 'User',
    'banker': 'Banker',
    'admin': 'Admin',
    'dont_have_account': "Don't have an account?",
    'already_have_account': 'Already have an account?',
    'username': 'Username',
    'email': 'Email',
    'back': 'Back',
    
    // Notification System
    'just_now': 'Just now',
    'minutes_ago': '{minutes}m ago',
    'hours_ago': '{hours}h ago',
    'days_ago': '{days}d ago',
    'loan_approved': 'Loan Approved',
    'loan_application_approved': 'Your loan application for {amount} has been approved.',
    'payment_due': 'Payment Due',
    'payment_due_message': 'Your loan payment of {amount} is due in 3 days.',
    'payment_received': 'Payment Received',
    'payment_received_message': 'We have received your loan payment of {amount}.',
    'loan_disbursed': 'Loan Disbursed',
    'loan_disbursed_message': 'Your loan of {amount} has been disbursed to your account.',
    
    // Banker Dashboard
    'banker_dashboard': 'Banker Dashboard',
    'all_users': 'All Users',
    'user_profile': 'User Profile',
    'name': 'Name',
    'email': 'Email',
    'phone': 'Phone',
    'address': 'Address',
    'occupation': 'Occupation',
    'role': 'Role',
    'credit_score': 'Credit Score',
    'credit_decision': 'Credit Decision',
    'loan_amount': 'Loan Amount',
    'message': 'Message',
    'uploaded_documents': 'Uploaded Documents',
    'no_documents_uploaded': 'No documents uploaded',
    'download': 'Download',
    'back_to_users': 'Back to Users',
    'documents': 'Documents',
    'search_users': 'Search users...',
    'all_scores': 'All Scores',
    'all_decisions': 'All Decisions',
    'refresh': 'Refresh',
    'actions': 'Actions',
    'view_details': 'View Details',
    'no_users_found': 'No users found matching your criteria',
    'no_documents': 'No documents',
    'score_justification': 'Score Justification',
    'clear_filters': 'Clear Filters',
    'total_users': 'Total Users',
    'filtered_users': 'Filtered Users',
    
    // Common terms
    'try_again': 'Try Again',
    'view_full_result': 'View Full Result',
    'minutes': 'minutes',
    'rupees': '₹',
    
    // Credit Score Analysis
    'credit_score_analysis': 'Credit Score Analysis',
    'analysis_generated_on': 'Analysis generated on',
    'score_range': 'Score Range',
    'next_review': 'Next Review',
    'days_30': '30 days',
    'score_justification': 'Score Justification',
    'detailed_analysis': 'Detailed Analysis',
    'positive_factors': 'Positive Factors',
    'negative_factors': 'Negative Factors',
    'recommendations': 'Recommendations',
    'maintain_regular_transactions': 'Maintain Regular Transactions',
    'maintain_regular_transactions_desc': 'Keep consistent spending patterns to build trust with lenders',
    'reduce_refunds_and_returns': 'Reduce Refunds and Returns',
    'reduce_refunds_and_returns_desc': 'Minimize transaction reversals to improve your financial reliability',
    'build_consistent_spending_pattern': 'Build Consistent Spending Pattern',
    'build_consistent_spending_pattern_desc': 'Establish regular spending habits to demonstrate financial stability',
    'excellent': 'Excellent',
    'good': 'Good',
    'fair': 'Fair',
    'poor': 'Poor',
    'no_data_available': 'No data available for analysis',
    'your_spending_is_stable_but_savings_are_low': 'Your spending is stable but savings are low',
    'your_financial_behavior_is_consistent': 'Your financial behavior is consistent',
    'your_financial_pattern_needs_improvement': 'Your financial pattern needs improvement',
    'excellent_score_description': 'Excellent credit score indicates strong financial reliability and trustworthiness',
    'good_score_description': 'Good credit score shows reliable financial behavior with minor improvements needed',
    'fair_score_description': 'Fair credit score suggests some financial inconsistencies that need attention',
    'poor_score_description': 'Poor credit score indicates significant financial reliability issues',
    'copy_score': 'Copy Score',
    'score_thresholds': 'Score Thresholds',
    'approve': 'Approve',
    'approve_with_cap': 'Approve with Cap',
    'review': 'Review',
    'reject': 'Reject',
    
    // Admin Dashboard
    'admin_dashboard': 'Admin Dashboard',
    'role': 'Role',
    'created_at': 'Created At',
    'edit': 'Edit',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'confirm_delete_user': 'Are you sure you want to delete this user? This action cannot be undone.',
    'user_profile': 'User Profile',
    'username': 'Username',
    'full_name': 'Full Name',

  },

  hi: {
    // Onboarding Screen
    'justifi': 'जस्टिफाई',
    'instant_micro_loans': 'रसीद का उपयोग करके तुरंत माइक्रो-ऋण',
    'get_approved': 'CIBIL या PAN के बिना मिनटों में स्वीकृति प्राप्त करें',
    'decision_time': '5 मिनट से भी कम समय में निर्णय',
    'no_pan_required': 'PAN/आधार की आवश्यकता नहीं है',
    'loan_amount': '₹10,000 तक के ऋण',
    'get_started': 'शुरू करें',
    'terms_consent': 'जारी रखकर, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत होते हैं',
    
    // Upload Screen
    'upload_documents': 'अपने दस्तावेज़ अपलोड करें',
    'upload_salary_receipt': 'अपनी वेतन रसीद अपलोड करें',
    'upload_salary_receipt_description': 'अपना क्रेडिट स्कोर गणना करने में मदद के लिए अपनी वेतन रसीद साझा करें',
    'upload_bank_statement': 'अपना बैंक स्टेटमेंट अपलोड करें',
    'upload_bank_statement_description': 'अपना क्रेडिट स्कोर गणना करने में मदद के लिए अपना बैंक स्टेटमेंट साझा करें',
    'choose_salary_receipt': 'वेतन रसीद चुनें',
    'choose_bank_statement': 'बैंक स्टेटमेंट चुनें',
    'upload_salary_receipt_button': 'वेतन रसीद अपलोड करें',
    'upload_bank_statement_button': 'बैंक स्टेटमेंट अपलोड करें',
    'salary_receipt_uploaded_successfully': 'वेतन रसीद सफलतापूर्वक अपलोड कर दी गई!',
    'bank_statement_uploaded_successfully': 'बैंक स्टेटमेंट सफलतापूर्वक अपलोड कर दिया गया!',
    'please_upload_at_least_one_document': 'कृपया कम से कम एक दस्तावेज़ अपलोड करें',
    'drag_drop_receipts': 'अपनी रसीद फ़ाइलों को यहाँ ड्रैग एंड ड्रॉप करें',
    'or': 'या',
    'choose_files': 'फ़ाइलें चुनें',
    'selected': 'चयनित',
    'or_try_demo': 'या डेमो डेटा के साथ प्रयास करें:',
    'use_demo_data': 'डेमो डेटा का उपयोग करें',
    'processing': 'प्रसंस्करण जारी है...',
    'calculate_my_score': 'मेरा स्कोर गणना करें',
    'no_pan_aadhaar_required': 'PAN/आधार की आवश्यकता नहीं है। आपका डेटा एन्क्रिप्टेड और सुरक्षित है।',
    'please_select_file': 'कृपया पहले एक फ़ाइल चुनें',
    'error_processing_request': 'आपके अनुरोध को संसाधित करने में त्रुटि। कृपया पुन: प्रयास करें।',
    'please_select_demo_user': 'कृपया एक डेमो उपयोगकर्ता चुनें',
    
    // Result Screen
    'your_credit_assessment': 'आपका क्रेडिट मूल्यांकन',
    'trust_score': 'ट्रस्टस्कोर',
    'top_reasons': 'शीर्ष कारण',
    'loan_offer': 'ऋण प्रस्ताव',
    'available_for_disbursement': 'तत्काल वितरण के लिए उपलब्ध',
    'accept_loan': 'ऋण स्वीकार करें',
    'loan_disbursed_success': '₹{amount} का ऋण सफलतापूर्वक वितरित कर दिया गया है!',
    'failed_to_disburse_loan': 'ऋण वितरित करने में विफल',
    'loan_approved': 'ऋण स्वीकृत!',
    'error': 'त्रुटि',
    'transaction_id': 'लेन-देन आईडी',
    'amount': 'राशि',
    'view_profile': 'प्रोफ़ाइल देखें',
    'loan_history': 'ऋण इतिहास',
    'spending_patterns': 'खर्च के पैटर्न',
    'settings': 'सेटिंग्स',
    'assess_another_person': 'दूसरे व्यक्ति का मूल्यांकन करें',
    'data_protected': 'आपका डेटा सुरक्षित है। हम इसका उपयोग केवल क्रेडिट मूल्यांकन के लिए करते हैं।',
    'approved': 'स्वीकृत',
    'approved_with_cap': 'कैप के साथ स्वीकृत',
    'under_review': 'समीक्षा में',
    'rejected': 'अस्वीकृत',
    'pending': 'लंबित',
    'loading': 'लोड हो रहा है',
    'hundred': '100',
    
    // Profile Screen
    'user_profile': 'उपयोगकर्ता प्रोफ़ाइल',
    'user': 'उपयोगकर्ता',
    'user_initial': 'उ',
    'email': 'ईमेल',
    'phone': 'फ़ोन',
    'address': 'पता',
    'occupation': 'व्यवसाय',
    'not_provided': 'प्रदान नहीं किया गया',
    'edit_profile': 'प्रोफ़ाइल संपादित करें',
    'upload_document': 'दस्तावेज़ अपलोड करें',
    'view_notifications': 'सूचनाएँ',
    'view_loan_history': 'ऋण इतिहास देखें',
    'view_spending_patterns': 'खर्च के पैटर्न देखें',
    'app_settings': 'ऐप सेटिंग्स',
    'logout': 'लॉग आउट',
    'mark_all_as_read': 'सभी को पढ़ा हुआ चिह्नित करें',
    'no_notifications': 'कोई सूचनाएँ नहीं',
    'unread': 'अपठित',
    'full_name': 'पूरा नाम',
    'enter_full_name': 'अपना पूरा नाम दर्ज करें',
    'enter_email': 'अपना ईमेल दर्ज करें',
    'enter_phone_number': 'अपना फ़ोन नंबर दर्ज करें',
    'enter_address': 'अपना पता दर्ज करें',
    'enter_occupation': 'अपना व्यवसाय दर्ज करें',
    'cancel': 'रद्द करें',
    'save_changes': 'परिवर्तन सहेजें',
    'back': 'वापस',
    'notifications_feature_coming_soon': 'सूचनाएँ सुविधा जल्द आ रही है!',
    
    // Loan History Screen
    'loading_loan_history': 'ऋण इतिहास लोड हो रहा है',
    'no_loan_history_found': 'कोई ऋण इतिहास नहीं मिला',
    'disbursed': 'वितरित',
    'repaid': 'चुका दिया गया',
    'repayment_due': 'पुनर्भुगतान की तिथि',
    
    // Spending Patterns Screen
    'spending_patterns_title': 'खर्च के पैटर्न',
    'loading_spending_patterns': 'खर्च के पैटर्न लोड हो रहे हैं',
    'daily': 'दैनिक',
    'weekly': 'साप्ताहिक',
    'monthly': 'मासिक',
    'spending_by_category': 'श्रेणी के अनुसार खर्च',
    'spending_summary': 'खर्च का सारांश',
    'groceries': 'किराने का सामान',
    'transport': 'परिवहन',
    'entertainment': 'मनोरंजन',
    'utilities': 'उपयोगिताएँ',
    'dining': 'भोजन',
    'other': 'अन्य',
    'rent': 'किराया',
    'user_diary': 'उपयोगकर्ता डायरी',
    'add_financial_note': 'एक वित्तीय नोट या गतिविधि जोड़ें...',
    'add_entry': 'प्रविष्टि जोड़ें',
    'delete': 'हटाएँ',
    'no_diary_entries': 'अभी तक कोई डायरी प्रविष्टि नहीं है। अपना पहला वित्तीय नोट जोड़ें!',
    
    // Settings Screen
    'notifications': 'सूचनाएँ',
    'enable_notifications': 'सूचनाएँ सक्षम करें',
    'email_notifications': 'ईमेल सूचनाएँ',
    'sms_notifications': 'एसएमएस सूचनाएँ',
    'appearance': 'उपस्थिति',
    'dark_mode': 'डार्क मोड',
    'view_mode': 'दृश्य मोड',
    'mobile_view': 'मोबाइल दृश्य',
    'desktop_view': 'डेस्क्टॉप दृश्य',
    'preferences': 'प्राथमिकताएँ',
    'language': 'भाषा',
    'currency': 'मुद्रा',
    'english': 'अंग्रेज़ी',
    'hindi': 'हिंदी',
    'tamil': 'तमिल',
    'telugu': 'तेलुगू',
    'kannada': 'कन्नड़',
    'indian_rupee': 'भारतीय रुपया (₹)',
    'us_dollar': 'अमेरिकी डॉलर ($)',
    'euro': 'यूरो (€)',
    'reset_to_default': 'डिफ़ॉल्ट पर रीसेट करें',
    'save_settings': 'सेटिंग्स सहेजें',
    'settings_saved_successfully': 'सेटिंग्स सफलतापूर्वक सहेजी गईं!',
    
    // Login/Signup Screen
    'login': 'लॉग इन करें',
    'signup': 'साइन अप करें',
    'username': 'उपयोगकर्ता नाम',
    'email_or_username': 'ईमेल या उपयोगकर्ता नाम',
    'email': 'ईमेल',
    'password': 'पासवर्ड',
    'confirm_password': 'पासवर्ड की पुष्टि करें',
    'passwords_do_not_match': 'पासवर्ड मेल नहीं खाते',
    'dont_have_account': 'क्या आपके पास खाता नहीं है?',
    'already_have_account': 'क्या आपके पास पहले से एक खाता है?',
    'select_your_role': 'अपनी भूमिका चुनें',
    'signup_as_user': 'उपयोगकर्ता के रूप में साइन अप करें',
    'user_role_description': 'माइक्रो-ऋण के लिए आवेदन करें और अपनी वित्तीय प्रोफ़ाइल प्रबंधित करें',
    'signup_as_banker': 'बैंकर के रूप में साइन अप करें',
    'banker_role_description': 'ऋण आवेदन की समीक्षा करें और वितरण प्रबंधित करें',
    'signup_as_admin': 'व्यवस्थापक के रूप में साइन अप करें',
    'admin_role_description': 'प्लेटफ़ॉर्म और उपयोगकर्ता खातों का प्रबंधन करें',
    'back': 'वापस',
    'select_role_to_continue': 'जारी रखने के लिए भूमिका चुनें',
    'no_role_selected': 'कोई भूमिका चयनित नहीं',
    'selected_role': 'चयनित भूमिका',
    'user': 'उपयोगकर्ता',
    'banker': 'बैंकर',
    'admin': 'व्यवस्थापक',
    'change': 'बदलें',
    
    // Notification System
    'just_now': 'अभी',
    'minutes_ago': '{minutes} मिनट पहले',
    'hours_ago': '{hours} घंटे पहले',
    'days_ago': '{days} दिन पहले',
    'loan_approved': 'ऋण स्वीकृत',
    'loan_application_approved': 'आपका ₹{amount} के लिए ऋण आवेदन स्वीकृत कर लिया गया है।',
    'payment_due': 'भुगतान की तिथि',
    'payment_due_message': 'आपका ₹{amount} का ऋण भुगतान 3 दिनों में नियत है।',
    'payment_received': 'भुगतान प्राप्त',
    'payment_received_message': 'हमें आपका ₹{amount} का ऋण भुगतान प्राप्त हो गया है।',
    'loan_disbursed': 'ऋण वितरित',
    'loan_disbursed_message': 'आपका ₹{amount} का ऋण आपके खाते में वितरित कर दिया गया है।',
    
    // Banker Dashboard
    'banker_dashboard': 'बैंकर डैशबोर्ड',
    'all_users': 'सभी उपयोगकर्ता',
    'user_profile': 'उपयोगकर्ता प्रोफ़ाइल',
    'name': 'नाम',
    'email': 'ईमेल',
    'phone': 'फ़ोन',
    'address': 'पता',
    'occupation': 'व्यवसाय',
    'role': 'भूमिका',
    'credit_score': 'क्रेडिट स्कोर',
    'credit_decision': 'क्रेडिट निर्णय',
    'loan_amount': 'ऋण राशि',
    'message': 'संदेश',
    'uploaded_documents': 'अपलोड किए गए दस्तावेज़',
    'no_documents_uploaded': 'कोई दस्तावेज़ अपलोड नहीं किए गए',
    'download': 'डाउनलोड करें',
    'back_to_users': 'उपयोगकर्ताओं के पास वापस जाएं',
    'documents': 'दस्तावेज़',
    'search_users': 'उपयोगकर्ताओं की खोज करें...',
    'all_scores': 'सभी स्कोर',
    'all_decisions': 'सभी निर्णय',
    'refresh': 'रीफ्रेश करें',
    'actions': 'कार्रवाई',
    'view_details': 'विवरण देखें',
    'no_users_found': 'आपके मानदंडों के अनुरूप कोई उपयोगकर्ता नहीं मिला',
    'no_documents': 'कोई दस्तावेज़ नहीं',
    'score_justification': 'स्कोर औचित्य',
    'clear_filters': 'फ़िल्टर साफ़ करें',
    'total_users': 'कुल उपयोगकर्ता',
    'filtered_users': 'फ़िल्टर किए गए उपयोगकर्ता',
    
    // Common terms
    'try_again': 'पुनः प्रयास करें',
    'view_full_result': 'पूर्ण परिणाम देखें',
    'minutes': 'मिनट',
    'rupees': '₹',
    
    // Credit Score Analysis
    'credit_score_analysis': 'क्रेडिट स्कोर विश्लेषण',
    'analysis_generated_on': 'विश्लेषण उत्पन्न हुआ',
    'score_range': 'स्कोर रेंज',
    'next_review': 'अगली समीक्षा',
    'days_30': '30 दिन',
    'score_justification': 'स्कोर औचित्य',
    'detailed_analysis': 'विस्तृत विश्लेषण',
    'positive_factors': 'सकारात्मक कारक',
    'negative_factors': 'नकारात्मक कारक',
    'recommendations': 'अनुशंसाएँ',
    'maintain_regular_transactions': 'नियमित लेनदेन बनाए रखें',
    'maintain_regular_transactions_desc': 'उधारदाताओं के साथ विश्वास बनाए रखने के लिए नियमित खर्च पैटर्न बनाए रखें',
    'reduce_refunds_and_returns': 'रिफंड और रिटर्न को कम करें',
    'reduce_refunds_and_returns_desc': 'अपनी वित्तीय विश्वसनीयता में सुधार करने के लिए लेनदेन उलटफेर को कम करें',
    'build_consistent_spending_pattern': 'स्थिर खर्च पैटर्न बनाएं',
    'build_consistent_spending_pattern_desc': 'वित्तीय स्थिरता को प्रदर्शित करने के लिए नियमित खर्च आदतें स्थापित करें',
    'excellent': 'उत्कृष्ट',
    'good': 'अच्छा',
    'fair': 'उचित',
    'poor': 'खराब',
    'no_data_available': 'विश्लेषण के लिए कोई डेटा उपलब्ध नहीं है',
    'your_spending_is_stable_but_savings_are_low': 'आपका खर्च स्थिर है लेकिन बचत कम है',
    'your_financial_behavior_is_consistent': 'आपका वित्तीय व्यवहार स्थिर है',
    'your_financial_pattern_needs_improvement': 'आपके वित्तीय पैटर्न को सुधार की आवश्यकता है',
    'excellent_score_description': 'उत्कृष्ट क्रेडिट स्कोर मजबूत वित्तीय विश्वसनीयता और विश्वसनीयता का संकेत देता है',
    'good_score_description': 'अच्छा क्रेडिट स्कोर छोटे सुधारों की आवश्यकता वाले विश्वसनीय वित्तीय व्यवहार को दर्शाता है',
    'fair_score_description': 'उचित क्रेडिट स्कोर कुछ वित्तीय असंगतियों का सुझाव देता है जिन पर ध्यान देने की आवश्यकता है',
    'poor_score_description': 'खराब क्रेडिट स्कोर महत्वपूर्ण वित्तीय विश्वसनीयता समस्याओं का संकेत देता है',
    'copy_score': 'स्कोर कॉपी करें',
    'score_thresholds': 'स्कोर थ्रेशोल्ड',
    'approve': 'स्वीकृत करें',
    'approve_with_cap': 'कैप के साथ स्वीकृत करें',
    'review': 'समीक्षा',
    'reject': 'अस्वीकार करें'
  },

  ta: {
    // Onboarding Screen
    'justifi': 'ஜஸ்டிஃபி',
    'instant_micro_loans': 'ரசீதுகளைப் பயன்படுத்தி உடனடி மைக்ரோ-கடன்கள்',
    'get_approved': 'CIBIL அல்லாமல் நிமிடங்களில் அங்கீகரிக்கப்படுவீர்கள்',
    'decision_time': '5 நிமிடங்களுக்குள் முடிவு',
    'no_pan_required': 'PAN/ஆதார் தேவையில்லை',
    'loan_amount': '₹10,000 வரை கடன்கள்',
    'get_started': 'தொடங்குங்கள்',
    'terms_consent': 'தொடருவதன் மூலம், எங்கள் சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்கிறீர்கள்',
    
    // Upload Screen
    'upload_documents': 'உங்கள் ஆவணங்களை பதிவேற்றவும்',
    'upload_salary_receipt': 'உங்கள் சம்பள ரசீதை பதிவேற்றவும்',
    'upload_salary_receipt_description': 'உங்கள் கடன் ஸ்கோரை கணக்கிட உதவ உங்கள் சம்பள ரசீதை பகிர்ந்து கொள்ளுங்கள்',
    'upload_bank_statement': 'உங்கள் வங்கி அறிக்கையை பதிவேற்றவும்',
    'upload_bank_statement_description': 'உங்கள் கடன் ஸ்கோரை கணக்கிட உதவ உங்கள் வங்கி அறிக்கையை பகிர்ந்து கொள்ளுங்கள்',
    'choose_salary_receipt': 'சம்பள ரசீதைத் தேர்ந்தெடுக்கவும்',
    'choose_bank_statement': 'வங்கி அறிக்கையைத் தேர்ந்தெடுக்கவும்',
    'upload_salary_receipt_button': 'சம்பள ரசீதை பதிவேற்றவும்',
    'upload_bank_statement_button': 'வங்கி அறிக்கையை பதிவேற்றவும்',
    'salary_receipt_uploaded_successfully': 'சம்பள ரசீது வெற்றிகரமாக பதிவேற்றப்பட்டது!',
    'bank_statement_uploaded_successfully': 'வங்கி அறிக்கை வெற்றிகரமாக பதிவேற்றப்பட்டது!',
    'please_upload_at_least_one_document': 'குறைந்தது ஒரு ஆவணத்தையாவது பதிவேற்றவும்',
    'drag_drop_receipts': 'உங்கள் ரசீது கோப்புகளை இங்கே இழுத்து விடவும்',
    'or': 'அல்லது',
    'choose_files': 'கோப்புகளைத் தேர்ந்தெடுக்கவும்',
    'selected': 'தேர்ந்தெடுக்பட்டது',
    'or_try_demo': 'அல்லது டெமோ தரவுடன் முயற்சிக்கவும்:',
    'use_demo_data': 'டெமோ தரவைப் பயன்படுத்தவும்',
    'processing': 'செயலாக்கம்...',
    'calculate_my_score': 'எனது ஸ்கோரை கணக்கிடு',
    'no_pan_aadhaar_required': 'PAN/ஆதார் தேவையில்லை. உங்கள் தரவு மறைகுறியாக்கம் செய்யப்பட்டு பாதுகாப்பாக உள்ளது.',
    'please_select_file': 'முதலில் ஒரு கோப்பைத் தேர்ந்தெடுக்கவும்',
    'error_processing_request': 'உங்கள் கோரிக்கையை செயலாக்குவதில் பிழை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    'please_select_demo_user': 'ஒரு டெமோ பயனரைத் தேர்ந்தெடுக்கவும்',
    
    // Result Screen
    'your_credit_assessment': 'உங்கள் கடன் மதிப்பீடு',
    'trust_score': 'ட்ரஸ்ட்ஸ்கோர்',
    'top_reasons': 'முக்கிய காரணங்கள்',
    'loan_offer': 'கடன் வாய்ப்பு',
    'available_for_disbursement': 'உடனடி விநியோகத்திற்கு கிடைக்றது',
    'accept_loan': 'கடனை ஏற்கவும்',
    'loan_disbursed_success': '₹{amount} கடன் வெற்றிகரமாக வழங்கப்பட்டது!',
    'failed_to_disburse_loan': 'கடனை வழங்க முடியவில்லை',
    'loan_approved': 'கடன் அங்கீகரிக்கப்பட்டது!',
    'error': 'பிழை',
    'transaction_id': 'பரிவர்த்தனை ஐடி',
    'amount': 'தொகை',
    'view_profile': 'சுயவிவரத்தை பார்க்கவும்',
    'loan_history': 'கடன் வரலாறு',
    'spending_patterns': 'செலவு முறைகள்',
    'settings': 'அமைப்புகள்',
    'assess_another_person': 'மற்றொரு நபரை மதிப்பீடு செய்யவும்',
    'data_protected': 'உங்கள் தரவு பாதுகாக்கப்பட்டுள்ளது. கடன் மதிப்பீட்டிற்கு மட்டுமே பயன்படுத்தப்படுகிறது.',
    'approved': 'அங்கீகரிக்கப்பட்டது',
    'approved_with_cap': 'கேப்புடன் அங்கீகரிக்கப்பட்டது',
    'under_review': 'மதிப்பாய்வில்',
    'rejected': 'நிராகரிக்கப்பட்டது',
    'pending': 'நிலுவையில்',
    'loading': 'ஏற்றுகிறது',
    'hundred': '100',
    
    // Profile Screen
    'user_profile': 'பயனர் சுயவிவரம்',
    'user': 'பயனர்',
    'user_initial': 'ப',
    'email': 'மின்னஞ்சல்',
    'phone': 'தொலைபேசி',
    'address': 'முகவரி',
    'occupation': 'தொழில்',
    'not_provided': 'வழங்கப்படவில்லை',
    'edit_profile': 'சுயவிவரத்தை திருத்தவும்',
    'upload_document': 'ஆவணத்தை பதிவேற்றவும்',
    'view_notifications': 'அறிவிப்புகள்',
    'view_loan_history': 'கடன் வரலாற்றை பார்க்கவும்',
    'view_spending_patterns': 'செலவு முறைகளை பார்க்கவும்',
    'app_settings': 'செயலிக்கான அமைப்புகள்',
    'logout': 'வெளியேறு',
    'mark_all_as_read': 'அனைத்தையும் வாசித்ததாக குறிக்கவும்',
    'no_notifications': 'அறிவிப்புகள் எதுவுமில்லை',
    'unread': 'படிக்காதது',
    'full_name': 'முழு பெயர்',
    'enter_full_name': 'உங்கள் முழு பெயரை உள்ளிடவும்',
    'enter_email': 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    'enter_phone_number': 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
    'enter_address': 'உங்கள் முகவரியை உள்ளிடவும்',
    'enter_occupation': 'உங்கள் தொழிலை உள்ளிடவும்',
    'cancel': 'ரத்து செய்',
    'save_changes': 'மாற்றங்களை சேமி',
    'back': 'மீண்டும்',
    'notifications_feature_coming_soon': 'அறிவிப்புகள் விளைவுகிறது!',
    
    // Loan History Screen
    'loading_loan_history': 'கடன் வரலாறு ஏற்றப்படுகிறது',
    'no_loan_history_found': 'கடன் வரலாறு எதுவும் கிடைக்கவில்லை',
    'disbursed': 'வழங்கப்பட்டது',
    'repaid': 'மீள் செலுத்தப்பட்டது',
    'repayment_due': 'மீள் செலுத்த வேண்டியது',
    
    // Spending Patterns Screen
    'spending_patterns_title': 'செலவு முறைகள்',
    'loading_spending_patterns': 'செலவு முறைகள் ஏற்றப்படுகின்றன',
    'daily': 'தினசரி',
    'weekly': 'வாரந்தோறும்',
    'monthly': 'மாதந்தோறும்',
    'spending_by_category': 'வகைப்படி செலவு',
    'spending_summary': 'செலவு சுருக்கம்',
    'groceries': 'கிராசரிகள்',
    'transport': 'போக்குவரத்து',
    'entertainment': 'பொழுதுபோக்கு',
    'utilities': 'சேவைகள்',
    'dining': 'உணவு',
    'other': 'மற்றவை',
    'rent': 'வாடகை',
    'user_diary': 'பயனர் குறிப்பேடு',
    'add_financial_note': 'ஒரு நிதிக் குறிப்பை அல்லது செயல்பாட்டைச் சேர்க்கவும்...',
    'add_entry': 'உள்ளீட்டைச் சேர்க்கவும்',
    'delete': 'அழி',
    'no_diary_entries': 'இதுவரை குறிப்பேட்டு உள்ளீடுகள் எதுவும் இல்லை. உங்கள் முதல் நிதிக் குறிப்பைச் சேர்க்கவும்!',
    
    // Settings Screen
    'notifications': 'அறிவிப்புகள்',
    'enable_notifications': 'அறிவிப்புகளை இயக்கவும்',
    'email_notifications': 'மின்னஞ்சல் அறிவிப்புகள்',
    'sms_notifications': 'SMS அறிவிப்புகள்',
    'appearance': 'தோற்றம்',
    'dark_mode': 'இருண்ட பயன்முறை',
    'view_mode': 'காட்சி முறை',
    'mobile_view': 'மொபைல் காட்சி',
    'desktop_view': 'டெஸ்க்டாப் காட்சி',
    'preferences': 'விருப்பத்தேர்வுகள்',
    'language': 'மொழி',
    'currency': 'நாணயம்',
    'english': 'ஆங்கிலம்',
    'hindi': 'ஹிந்தி',
    'tamil': 'தமிழ்',
    'telugu': 'தெலுங்கு',
    'kannada': 'கன்னடம்',
    'indian_rupee': 'இந்திய ரூபாய் (₹)',
    'us_dollar': 'அமெரிக்க டாலர் ($)',
    'euro': 'யூரோ (€)',
    'reset_to_default': 'இயல்புநிலைக்கு மீட்டமை',
    'save_settings': 'அமைப்புகளை சேமி',
    'settings_saved_successfully': 'அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டது!',
    
    // Login/Signup Screen
    'login': 'உள்நுழைக',
    'signup': 'பதிவு செய்யவும்',
    'username': 'பயனர்பெயர்',
    'email_or_username': 'மின்னஞ்சல் அல்லது பயனர்பெயர்',
    'email': 'மின்னஞ்சல்',
    'password': 'கடவுச்சொல்',
    'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'passwords_do_not_match': 'கடவுச்சொறகள் பொருந்தவில்லை',
    'dont_have_account': 'கணக்கு இல்லையா?',
    'already_have_account': 'ஏற்கனவே ஒரு கணக்கு உள்ளதா?',
    'select_your_role': 'உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்',
    'signup_as_user': 'பயனராக பதிவு செய்யவும்',
    'user_role_description': 'மைக்ரோ-கடன்களுக்கு விண்ணப்பிக்கவும் உங்கள் நிதித் தன்மையை நிர்வகிக்கவும்',
    'signup_as_banker': 'வங்கியாளராக பதிவு செய்யவும்',
    'banker_role_description': 'கடன் விண்ணப்பங்களை மதிப்பாய்வு செய்து விநியோகங்களை நிர்வகிக்கவும்',
    'signup_as_admin': 'நிர்வாகியாக பதிவு செய்யவும்',
    'admin_role_description': 'தளத்தையும் பயனர் கணக்குகளையும் நிர்வகிக்கவும்',
    'back': 'மீண்டும்',
    'select_role_to_continue': 'தொடர பங்கைத் தேர்ந்தெடுக்கவும்',
    'no_role_selected': 'பங்கு எதுவும் தேர்ந்தெடுக்கப்படவில்லை',
    'selected_role': 'தேர்ந்தெடுக்கப்பட்ட பங்கு',
    'user': 'பயனர்',
    'banker': 'வங்கியாளர்',
    'admin': 'நிர்வாகி',
    'change': 'மாற்று',
    
    // Notification System
    'just_now': 'இப்போது',
    'minutes_ago': '{minutes} நிமிடங்களுக்கு முன்',
    'hours_ago': '{hours} மணி நேரம் முன்',
    'days_ago': '{days} நாட்களுக்கு முன்',
    'loan_approved': 'கடன் அங்கீகரிக்கப்பட்டது',
    'loan_application_approved': 'உங்கள் ₹{amount}க்கான கடன் விண்ணப்பம் அங்கீகரிக்கப்பட்டது.',
    'payment_due': 'செலுத்த வேண்டியது',
    'payment_due_message': 'உங்கள் ₹{amount} கடன் கொடுப்பனவு 3 நாட்களில் நிலுவையில் உள்ளது.',
    'payment_received': 'கொடுப்பனவு பெறப்பட்டது',
    'payment_received_message': 'உங்கள் ₹{amount} கடன் கொடுப்பனவை நாங்கள் பெற்றுள்ளோம்.',
    'loan_disbursed': 'கடன் வழங்கப்பட்டது',
    'loan_disbursed_message': 'உங்கள் ₹{amount} கடன் உங்கள் கணக்கில் வழங்கப்பட்டுள்ளது.',
    
    // Banker Dashboard
    'banker_dashboard': 'வங்கியாளர் டாஷ்போர்ட்',
    'all_users': 'அனைத்து பயனர்கள்',
    'user_profile': 'பயனர் சுயவிவரம்',
    'name': 'பெயர்',
    'email': 'மின்னஞ்சல்',
    'phone': 'தொலைபேசி',
    'address': 'முகவரி',
    'occupation': 'தொழில்',
    'role': 'பங்கு',
    'credit_score': 'கடன் மதிப்பீடு',
    'credit_decision': 'கடன் முடிவு',
    'loan_amount': 'கடன் தொகை',
    'message': 'செய்தி',
    'uploaded_documents': 'பதிவேற்றப்பட்ட ஆவணங்கள்',
    'no_documents_uploaded': 'ஆவணங்கள் எதுவும் பதிவேற்றப்படவில்லை',
    'download': 'பதிவிறக்கம்',
    'back_to_users': 'பயனர்களிடம் திரும்பு',
    'documents': 'ஆவணங்கள்',
    'search_users': 'பயனர்களைத் தேடு...',
    'all_scores': 'அனைத்து மதிப்பீடுகள்',
    'all_decisions': 'அனைத்து முடிவுகள்',
    'refresh': 'புதுப்பி',
    'actions': 'செயல்கள்',
    'view_details': 'விவரங்களைப் பார்க்கவும்',
    'no_users_found': 'உங்கள் தேடல் மாநிலைக்குப் பொருந்தும் பயனர்கள் எதுவும் கிடைக்கவில்லை',
    'no_documents': 'ஆவணங்கள் இல்லை',
    'score_justification': 'மதிப்பீட்டு நியாயப்படுத்தல்',
    'clear_filters': 'வடிப்பான்களை அழிக்கவும்',
    'total_users': 'மொத்த பயனர்கள்',
    'filtered_users': 'வடிகட்டப்பட்ட பயனர்கள்',
    
    // Common terms
    'try_again': 'மீண்டும் முயற்சிக்கவும்',
    'view_full_result': 'முழு முடிவைக் காண்க',
    'minutes': 'நிமிடங்கள்',
    'rupees': '₹',
      
    // Credit Score Analysis
    'credit_score_analysis': 'கடன் மதிப்பீட்டு ஆய்வு',
    'analysis_generated_on': 'ஆய்வு உருவாக்கப்பட்டது',
    'score_range': 'மதிப்பீட்டு வீச்சு',
    'next_review': 'அடுத்த மதிப்பீடு',
    'days_30': '30 நாட்கள்',
    'score_justification': 'மதிப்பீட்டு நியாயப்படுத்தல்',
    'detailed_analysis': 'விரிவான ஆய்வு',
    'positive_factors': 'நேர்மறை காரணிகள்',
    'negative_factors': 'எதிர்மறை காரணிகள்',
    'recommendations': 'பரிந்துரைகள்',
    'maintain_regular_transactions': 'வழக்கமான பரிவர்த்தனைகளை பராமரிக்கவும்',
    'maintain_regular_transactions_desc': 'கடன் வழங்குநர்களுடன் நம்பிக்கையை கட்டியெழுப்ப ஒழுங்கான செலவு முறைகளை பராமரிக்கவும்',
    'reduce_refunds_and_returns': 'திருப்பிதரவுகள் மற்றும் திரும்பப் பெறுதல்களை குறைக்கவும்',
    'reduce_refunds_and_returns_desc': 'உங்கள் நிதி நம்பகத்தன்மையை மேம்படுத்த பரிவர்த்தனை தலைகீழ்களை குறைக்கவும்',
    'build_consistent_spending_pattern': 'ஒழுங்கான செலவு முறையை உருவாக்கவும்',
    'build_consistent_spending_pattern_desc': 'நிதி நிலைத்தன்மையை வெளிப்படுத்த வழக்கமான செலவு பழக்கவழக்கங்களை உருவாக்கவும்',
    'excellent': 'சிறப்பான',
    'good': 'நல்ல',
    'fair': 'நல்ல',
    'poor': 'மோசமான',
    'no_data_available': 'ஆய்வுக்கு தரவு கிடைக்கவில்லை',
    'your_spending_is_stable_but_savings_are_low': 'உங்கள் செலவு நிலையானது ஆனால் சேமிப்புகள் குறைவாக உள்ளது',
    'your_financial_behavior_is_consistent': 'உங்கள் நிதி நடத்தை ஒழுங்கானது',
    'your_financial_pattern_needs_improvement': 'உங்கள் நிதி முறைக்கு மேம்பாடு தேவை',
    'excellent_score_description': 'சிறப்பான கடன் மதிப்பீடு வலுவான நிதி நம்பகத்தன்மை மற்றும் நம்பகத்தன்மையை குறிக்கிறது',
    'good_score_description': 'நல்ல கடன் மதிப்பீடு சிறிய மேம்பாடுகள் தேவையான நம்பகமான நிதி நடத்தையை காட்டுகிறது',
    'fair_score_description': 'நல்ல கடன் மதிப்பீடு கவனம் செலுத்த வேண்டிய சில நிதி முரண்பாடுகளை குறிப்பிடுகிறது',
    'poor_score_description': 'மோசமான கடன் மதிப்பீடு முக்கியமான நிதி நம்பகத்தன்மை சிக்கல்களை குறிக்கிறது',
    'copy_score': 'மதிப்பை நகலெடு',
    'score_thresholds': 'மதிப்பீட்டு வாசல்கள்',
    'approve': 'அங்கீகரி',
    'approve_with_cap': 'கேப்புடன் அங்கீகரி',
    'review': 'மதிப்பாய்வு',
    'reject': 'நிராகரி'
  }
};

// Function to get translated text
export const t = (key, language = 'en') => {
  return translations[language]?.[key] || translations['en']?.[key] || key;
};
