// Localization dictionary
const translations = {
  en: {
    // Onboarding Screen
    'justifi': 'JustiFi',
    'instant_micro_loans': 'Instant Micro-Loans Using Receipts',
    'get_approved': 'Get approved in minutes without CIBIL or PAN',
    'decision_time': 'Decision in under 5 minutes',
    'no_pan_required': 'No PAN/Aadhaar required',
    'loan_amount': 'Loans up to ₹10,000',
    'get_started': 'Get Started',
    'terms_consent': 'By continuing, you agree to our Terms of Service and Privacy Policy',
    
    // Upload Screen
    'upload_documents': 'Upload Documents',
    'upload_salary_receipt': 'Upload Salary Receipt',
    'upload_salary_receipt_description': 'Please upload your latest salary receipt for credit assessment',
    'choose_salary_receipt': 'Choose Salary Receipt',
    'upload_salary_receipt_button': 'Upload Salary Receipt',
    'upload_bank_statement': 'Upload Bank Statement',
    'upload_bank_statement_description': 'Please upload your recent bank statement for credit assessment',
    'choose_bank_statement': 'Choose Bank Statement',
    'upload_bank_statement_button': 'Upload Bank Statement',
    'upload_aadhar_card': 'Upload Aadhar Card',
    'upload_aadhar_card_description': 'Please upload your Aadhar card for additional verification (optional)',
    'choose_aadhar_card': 'Choose Aadhar Card',
    'upload_aadhar_card_button': 'Upload Aadhar Card',
    'upload_pan_card': 'Upload PAN Card',
    'upload_pan_card_description': 'Please upload your PAN card for additional verification (optional)',
    'choose_pan_card': 'Choose PAN Card',
    'upload_pan_card_button': 'Upload PAN Card',
    'upload_either_aadhar_or_pan': 'Upload Either Aadhar or PAN',
    'select_document_type': 'Select Document Type',
    'aadhar_card': 'Aadhar Card',
    'pan_card': 'PAN Card',
    'or_try_demo': 'Or try with demo data',
    'select_demo_user': 'Select Demo User',
    'please_select_demo_user': 'Please select a demo user',
    'calculate_my_score': 'Calculate My Score',
    'processing': 'Processing...',
    'please_upload_both_documents': 'Please upload both salary receipt and bank statement',
    'salary_receipt_uploaded_successfully': 'Salary receipt uploaded successfully',
    'bank_statement_uploaded_successfully': 'Bank statement uploaded successfully',
    'id_document_uploaded_successfully': 'ID document uploaded successfully',
    'please_select_file': 'Please select a file to upload',
    'please_upload_at_least_one_document': 'Please upload at least one document or select a demo user',
    'error_processing_request': 'Error processing request',
    'no_pan_aadhaar_required': 'No PAN or Aadhaar required. We protect your privacy.',
    'restart_upload': 'Upload Different Documents',
    
    // Result Screen
    'your_credit_assessment': 'Your Credit Assessment',
    'trust_score': 'TrustScore',
    'top_reasons': 'Top Reasons',
    'loan_offer': 'Loan Offer',
    'available_for_disbursement': 'Available for immediate disbursement',
    'accept_loan': 'Accept Loan',
    'loan_disbursed_success': 'Loan of ₹{amount} has been successfully disbursed!',
    'failed_to_disburse_loan': 'Failed to disburse loan',
    'loan_approved': 'Loan Approved!',
    'error': 'Error',
    'transaction_id': 'Transaction ID',
    'amount': 'Amount',
    'view_profile': 'View Profile',
    'loan_history': 'Loan History',
    'spending_patterns': 'Spending Patterns',
    'settings': 'Settings',
    'assess_another_person': 'Assess Another Person',
    'data_protected': 'Your data is protected. We only use it for credit assessment.',
    'approved': 'Approved',
    'approved_with_cap': 'Approved with Cap',
    'under_review': 'Under Review',
    'rejected': 'Rejected',
    'pending': 'Pending',
    'loading': 'Loading',
    'hundred': '100',
    
    // New loan request strings
    'loan_request_submitted': 'Loan Request Submitted',
    'loan_status_pending_approval': 'Your loan request is pending approval from a banker.',
    'failed_to_submit_loan_request': 'Failed to submit loan request',
    'loan_status': 'Loan Status',
    'loan_request_rejected': 'Your loan request has been rejected.',
    'request_id': 'Request ID',
    'requested_amount': 'Requested Amount',
    'requested_on': 'Requested On',
    'loan_information': 'Loan Information',
    'submit_documents_for_assessment': 'Submit your documents for credit assessment to get loan offers.',
    'upload_documents': 'Upload Documents',
    'existing_loan_request': 'You have an existing loan request',
    'existing_loan_request_warning': 'You already have a loan request in the system.',
    'continue_anyway': 'Do you want to continue uploading new documents anyway?',
    'pending': 'Pending',
    'approved': 'Approved',
    'rejected': 'Rejected',
    
    // Profile Screen
    'user_profile': 'User Profile',
    'user': 'User',
    'user_initial': 'U',
    'email': 'Email',
    'phone': 'Phone',
    'address': 'Address',
    'occupation': 'Occupation',
    'not_provided': 'Not provided',
    'edit_profile': 'Edit Profile',
    'upload_document': 'Upload Document',
    'view_notifications': 'Notifications',
    'view_loan_history': 'View Loan History',
    'view_spending_patterns': 'View Spending Patterns',
    'app_settings': 'App Settings',
    'logout': 'Logout',
    'mark_all_as_read': 'Mark All as Read',
    'no_notifications': 'No notifications',
    'unread': 'Unread',
    'full_name': 'Full Name',
    'enter_full_name': 'Enter your full name',
    'enter_email': 'Enter your email',
    'enter_phone_number': 'Enter your phone number',
    'enter_address': 'Enter your address',
    'enter_occupation': 'Enter your occupation',
    'cancel': 'Cancel',
    'save_changes': 'Save Changes',
    'back': 'Back',
    'notifications_feature_coming_soon': 'Notifications feature is coming soon!',
    
    // Loan History Screen
    'loading_loan_history': 'Loading loan history',
    'no_loan_history_found': 'No loan history found',
    'disbursed': 'Disbursed',
    'repaid': 'Repaid',
    'repayment_due': 'Repayment Due',
    'error_loading_loan_history': 'Error loading loan history',
    
    // Spending Patterns Screen
    'spending_patterns_title': 'Spending Patterns',
    'loading_spending_patterns': 'Loading spending patterns',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'spending_by_category': 'Spending by Category',
    'spending_summary': 'Spending Summary',
    'groceries': 'Groceries',
    'transport': 'Transport',
    'entertainment': 'Entertainment',
    'utilities': 'Utilities',
    'dining': 'Dining',
    'other': 'Other',
    'rent': 'Rent',
    'user_diary': 'User Diary',
    'add_financial_note': 'Add a financial note or activity...',
    'add_entry': 'Add Entry',
    'delete': 'Delete',
    'no_diary_entries': 'No diary entries yet. Add your first financial note!',
    
    // Settings Screen
    'notifications': 'Notifications',
    'enable_notifications': 'Enable Notifications',
    'email_notifications': 'Email Notifications',
    'sms_notifications': 'SMS Notifications',
    'appearance': 'Appearance',
    'dark_mode': 'Dark Mode',
    'view_mode': 'View Mode',
    'mobile_view': 'Mobile View',
    'desktop_view': 'Desktop View',
    'preferences': 'Preferences',
    'language': 'Language',
    'currency': 'Currency',
    'english': 'English',
    'hindi': 'Hindi',
    'tamil': 'Tamil',
    'telugu': 'Telugu',
    'kannada': 'Kannada',
    'indian_rupee': 'Indian Rupee (₹)',
    'us_dollar': 'US Dollar ($)',
    'euro': 'Euro (€)',
    'reset_to_default': 'Reset to Default',
    'save_settings': 'Save Settings',
    'settings_saved_successfully': 'Settings saved successfully!',
    
    // Login/Signup
    'login': 'Login',
    'signup': 'Sign Up',
    'email_or_username': 'Email or Username',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'processing': 'Processing...',
    'passwords_do_not_match': 'Passwords do not match',
    'password_min_length': 'Password must be at least 6 characters long',
    'email_gmail_required': 'Email must be a valid Gmail address ending with @gmail.com',
    'select_your_role': 'Select Your Role',
    'signup_as_user': 'Signup as User',
    'user_role_description': 'Apply for micro-loans using receipt data',
    'signup_as_banker': 'Signup as Banker',
    'banker_role_description': 'Review loan applications and manage users',
    'signup_as_admin': 'Signup as Admin',
    'admin_role_description': 'Manage the platform and user accounts',
    'select_role_to_continue': 'Select Role to Continue',
    'no_role_selected': 'No role selected',
    'selected_role': 'Selected Role',
    'change': 'Change',
    'user': 'User',
    'banker': 'Banker',
    'admin': 'Admin',
    'dont_have_account': "Don't have an account?",
    'already_have_account': 'Already have an account?',
    'username': 'Username',
    'email': 'Email',
    'back': 'Back',
    
    // Notification System
    'just_now': 'Just now',
    'minutes_ago': '{minutes}m ago',
    'hours_ago': '{hours}h ago',
    'days_ago': '{days}d ago',
    'loan_approved': 'Loan Approved',
    'loan_application_approved': 'Your loan application for {amount} has been approved.',
    'payment_due': 'Payment Due',
    'payment_due_message': 'Your loan payment of {amount} is due in 3 days.',
    'payment_received': 'Payment Received',
    'payment_received_message': 'We have received your loan payment of {amount}.',
    'loan_disbursed': 'Loan Disbursed',
    'loan_disbursed_message': 'Your loan of {amount} has been disbursed to your account.',
    
    // Banker Dashboard
    'banker_dashboard': 'Banker Dashboard',
    'all_users': 'All Users',
    'user_profile': 'User Profile',
    'name': 'Name',
    'email': 'Email',
    'phone': 'Phone',
    'address': 'Address',
    'occupation': 'Occupation',
    'role': 'Role',
    'credit_score': 'Credit Score',
    'credit_decision': 'Credit Decision',
    'loan_amount': 'Loan Amount',
    'message': 'Message',
    'uploaded_documents': 'Uploaded Documents',
    'no_documents_uploaded': 'No documents uploaded',
    'download': 'Download',
    'back_to_users': 'Back to Users',
    'documents': 'Documents',
    'search_users': 'Search users...',
    'all_scores': 'All Scores',
    'all_decisions': 'All Decisions',
    'refresh': 'Refresh',
    'actions': 'Actions',
    'view_details': 'View Details',
    'no_users_found': 'No users found matching your criteria',
    'no_documents': 'No documents',
    'score_justification': 'Score Justification',
    'clear_filters': 'Clear Filters',
    'total_users': 'Total Users',
    'filtered_users': 'Filtered Users',
    
    // Common terms
    'try_again': 'Try Again',
    'view_full_result': 'View Full Result',
    'minutes': 'minutes',
    'rupees': '₹',
    
    // Credit Score Analysis
    'credit_score_analysis': 'Credit Score Analysis',
    'analysis_generated_on': 'Analysis generated on',
    'score_range': 'Score Range',
    'next_review': 'Next Review',
    'days_30': '30 days',
    'score_justification': 'Score Justification',
    'detailed_analysis': 'Detailed Analysis',
    'positive_factors': 'Positive Factors',
    'negative_factors': 'Negative Factors',
    'recommendations': 'Recommendations',
    'maintain_regular_transactions': 'Maintain Regular Transactions',
    'maintain_regular_transactions_desc': 'Keep consistent spending patterns to build trust with lenders',
    'reduce_refunds_and_returns': 'Reduce Refunds and Returns',
    'reduce_refunds_and_returns_desc': 'Minimize transaction reversals to improve your financial reliability',
    'build_consistent_spending_pattern': 'Build Consistent Spending Pattern',
    'build_consistent_spending_pattern_desc': 'Establish regular spending habits to demonstrate financial stability',
    'excellent': 'Excellent',
    'good': 'Good',
    'fair': 'Fair',
    'poor': 'Poor',
    'no_data_available': 'No data available for analysis',
    'your_spending_is_stable_but_savings_are_low': 'Your spending is stable but savings are low',
    'your_financial_behavior_is_consistent': 'Your financial behavior is consistent',
    'your_financial_pattern_needs_improvement': 'Your financial pattern needs improvement',
    'excellent_score_description': 'Excellent credit score indicates strong financial reliability and trustworthiness',
    'good_score_description': 'Good credit score shows reliable financial behavior with minor improvements needed',
    'fair_score_description': 'Fair credit score suggests some financial inconsistencies that need attention',
    'poor_score_description': 'Poor credit score indicates significant financial reliability issues',
    'copy_score': 'Copy Score',
    'score_thresholds': 'Score Thresholds',
    'approve': 'Approve',
    'approve_with_cap': 'Approve with Cap',
    'review': 'Review',
    'reject': 'Reject',
    
    // Admin Dashboard
    'admin_dashboard': 'Admin Dashboard',
    'role': 'Role',
    'created_at': 'Created At',
    'edit': 'Edit',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'confirm_delete_user': 'Are you sure you want to delete this user? This action cannot be undone.',
    'user_profile': 'User Profile',
    'username': 'Username',
    'full_name': 'Full Name',
  },

  hi: {
    // Onboarding Screen
    'justifi': 'जस्टिफाई',
    'instant_micro_loans': 'रसीद का उपयोग करके तुरंत माइक्रो-ऋण',
    'get_approved': 'CIBIL या PAN के बिना मिनटों में स्वीकृति प्राप्त करें',
    'decision_time': '5 मिनट से भी कम समय में निर्णय',
    'no_pan_required': 'PAN/आधार की आवश्यकता नहीं है',
    'loan_amount': '₹10,000 तक के ऋण',
    'get_started': 'शुरू करें',
    'terms_consent': 'जारी रखकर, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत होते हैं',
    
    // Upload Screen
    'upload_documents': 'अपने दस्तावेज़ अपलोड करें',
    'upload_salary_receipt': 'अपनी वेतन रसीद अपलोड करें',
    'upload_salary_receipt_description': 'अपना क्रेडिट स्कोर गणना करने में मदद के लिए अपनी वेतन रसीद साझा करें',
    'upload_bank_statement': 'अपना बैंक स्टेटमेंट अपलोड करें',
    'upload_bank_statement_description': 'अपना क्रेडिट स्कोर गणना करने में मदद के लिए अपना बैंक स्टेटमेंट साझा करें',
    'choose_salary_receipt': 'वेतन रसीद चुनें',
    'choose_bank_statement': 'बैंक स्टेटमेंट चुनें',
    'upload_salary_receipt_button': 'वेतन रसीद अपलोड करें',
    'upload_bank_statement_button': 'बैंक स्टेटमेंट अपलोड करें',
    'salary_receipt_uploaded_successfully': 'वेतन रसीद सफलतापूर्वक अपलोड कर दी गई!',
    'bank_statement_uploaded_successfully': 'बैंक स्टेटमेंट सफलतापूर्वक अपलोड कर दिया गया!',
    'please_upload_at_least_one_document': 'कृपया कम से कम एक दस्तावेज़ अपलोड करें',
    'drag_drop_receipts': 'अपनी रसीद फ़ाइलों को यहाँ ड्रैग एंड ड्रॉप करें',
    'or': 'या',
    'choose_files': 'फ़ाइलें चुनें',
    'selected': 'चयनित',
    'or_try_demo': 'या डेमो डेटा के साथ प्रयास करें:',
    'use_demo_data': 'डेमो डेटा का उपयोग करें',
    'processing': 'प्रसंस्करण जारी है...',
    'calculate_my_score': 'मेरा स्कोर गणना करें',
    'no_pan_aadhaar_required': 'PAN/आधार की आवश्यकता नहीं है। आपका डेटा एन्क्रिप्टेड और सुरक्षित है।',
    'please_select_file': 'कृपया पहले एक फ़ाइल चुनें',
    'error_processing_request': 'आपके अनुरोध को संसाधित करने में त्रुटि। कृपया पुन: प्रयास करें।',
    'please_select_demo_user': 'कृपया एक डेमो उपयोगकर्ता चुनें',
    
    // Result Screen
    'your_credit_assessment': 'आपका क्रेडिट मूल्यांकन',
    'trust_score': 'ट्रस्टस्कोर',
    'top_reasons': 'शीर्ष कारण',
    'loan_offer': 'ऋण प्रस्ताव',
    'available_for_disbursement': 'तत्काल वितरण के लिए उपलब्ध',
    'accept_loan': 'ऋण स्वीकार करें',
    'loan_disbursed_success': '₹{amount} का ऋण सफलतापूर्वक वितरित कर दिया गया है!',
    'failed_to_disburse_loan': 'ऋण वितरित करने में विफल',
    'loan_approved': 'ऋण स्वीकृत!',
    'error': 'त्रुटि',
    'transaction_id': 'लेन-देन आईडी',
    'amount': 'राशि',
    'view_profile': 'प्रोफ़ाइल देखें',
    'loan_history': 'ऋण इतिहास',
    'spending_patterns': 'खर्च के पैटर्न',
    'settings': 'सेटिंग्स',
    'assess_another_person': 'दूसरे व्यक्ति का मूल्यांकन करें',
    'data_protected': 'आपका डेटा सुरक्षित है। हम इसका उपयोग केवल क्रेडिट मूल्यांकन के लिए करते हैं।',
    'approved': 'स्वीकृत',
    'approved_with_cap': 'कैप के साथ स्वीकृत',
    'under_review': 'समीक्षा में',
    'rejected': 'अस्वीकृत',
    'pending': 'लंबित',
    'loading': 'लोड हो रहा है',
    'hundred': '100',
    
    // New loan request strings
    'loan_request_submitted': 'ऋण अनुरोध सबमिट किया गया',
    'loan_status_pending_approval': 'आपका ऋण अनुरोध बैंकर से अनुमोदन की प्रतीक्षा में है।',
    'failed_to_submit_loan_request': 'ऋण अनुरोध सबमिट करने में विफल',
    'loan_status': 'ऋण स्थिति',
    'loan_request_rejected': 'आपका ऋण अनुरोध अस्वीकार कर दिया गया है।',
    'request_id': 'अनुरोध आईडी',
    'requested_amount': 'अनुरोधित राशि',
    'requested_on': 'अनुरोध पर',
    'loan_information': 'ऋण सूचना',
    'submit_documents_for_assessment': 'ऋण प्रस्ताव प्राप्त करने के लिए अपने दस्तावेज़ क्रेडिट मूल्यांकन के लिए सबमिट करें।',
    'upload_documents': 'दस्तावेज़ अपलोड करें',
    
    // Profile Screen
    'user_profile': 'उपयोगकर्ता प्रोफ़ाइल',
    'user': 'उपयोगकर्ता',
    'user_initial': 'उ',
    'email': 'ईमेल',
    'phone': 'फ़ोन',
    'address': 'पता',
    'occupation': 'व्यवसाय',
    'not_provided': 'प्रदान नहीं किया गया',
    'edit_profile': 'प्रोफ़ाइल संपादित करें',
    'upload_document': 'दस्तावेज़ अपलोड करें',
    'view_notifications': 'सूचनाएँ',
    'view_loan_history': 'ऋण इतिहास देखें',
    'view_spending_patterns': 'खर्च के पैटर्न देखें',
    'app_settings': 'ऐप सेटिंग्स',
    'logout': 'लॉग आउट',
    'mark_all_as_read': 'सभी को पढ़ा हुआ चिह्नित करें',
    'no_notifications': 'कोई सूचनाएँ नहीं',
    'unread': 'अपठित',
    'full_name': 'पूरा नाम',
    'enter_full_name': 'अपना पूरा नाम दर्ज करें',
    'enter_email': 'अपना ईमेल दर्ज करें',
    'enter_phone_number': 'अपना फ़ोन नंबर दर्ज करें',
    'enter_address': 'अपना पता दर्ज करें',
    'enter_occupation': 'अपना व्यवसाय दर्ज करें',
    'cancel': 'रद्द करें',
    'save_changes': 'परिवर्तन सहेजें',
    'back': 'वापस',
    'notifications_feature_coming_soon': 'सूचनाएँ सुविधा जल्द आ रही है!',
    
    // Loan History Screen
    'loading_loan_history': 'ऋण इतिहास लोड हो रहा है',
    'no_loan_history_found': 'कोई ऋण इतिहास नहीं मिला',
    'disbursed': 'वितरित',
    'repaid': 'चुका दिया गया',
    'repayment_due': 'पुनर्भुगतान की तिथि',
    'error_loading_loan_history': 'ऋण इतिहास लोड करने में त्रुटि',
    
    // Spending Patterns Screen
    'spending_patterns_title': 'खर्च के पैटर्न',
    'loading_spending_patterns': 'खर्च के पैटर्न लोड हो रहे हैं',
    'daily': 'दैनिक',
    'weekly': 'साप्ताहिक',
    'monthly': 'मासिक',
    'spending_by_category': 'श्रेणी के अनुसार खर्च',
    'spending_summary': 'खर्च का सारांश',
    'groceries': 'किराने का सामान',
    'transport': 'परिवहन',
    'entertainment': 'मनोरंजन',
    'utilities': 'उपयोगिताएँ',
    'dining': 'भोजन',
    'other': 'अन्य',
    'rent': 'किराया',
    'user_diary': 'उपयोगकर्ता डायरी',
    'add_financial_note': 'एक वित्तीय नोट या गतिविधि जोड़ें...',
    'add_entry': 'प्रविष्टि जोड़ें',
    'delete': 'हटाएँ',
    'no_diary_entries': 'अभी तक कोई डायरी प्रविष्टि नहीं। अपना पहला वित्तीय नोट जोड़ें!',
    
    // Settings Screen
    'notifications': 'सूचनाएँ',
    'enable_notifications': 'सूचनाएँ सक्षम करें',
    'email_notifications': 'ईमेल सूचनाएँ',
    'sms_notifications': 'एसएमएस सूचनाएँ',
    'appearance': 'उपस्थिति',
    'dark_mode': 'डार्क मोड',
    'view_mode': 'दृश्य मोड',
    'mobile_view': 'मोबाइल दृश्य',
    'desktop_view': 'डेस्कटॉप दृश्य',
    'preferences': 'प्राथमिकताएँ',
    'language': 'भाषा',
    'currency': 'मुद्रा',
    'english': 'अंग्रेज़ी',
    'hindi': 'हिंदी',
    'tamil': 'तमिल',
    'telugu': 'तेलुगू',
    'kannada': 'कन्नड़',
    'indian_rupee': 'भारतीय रुपया (₹)',
    'us_dollar': 'अमेरिकी डॉलर ($)',
    'euro': 'यूरो (€)',
    'reset_to_default': 'डिफ़ॉल्ट पर रीसेट करें',
    'save_settings': 'सेटिंग्स सहेजें',
    'settings_saved_successfully': 'सेटिंग्स सफलतापूर्वक सहेजी गईं!',
    
    // Login/Signup
    'login': 'लॉगिन',
    'signup': 'साइन अप',
    'email_or_username': 'ईमेल या उपयोगकर्ता नाम',
    'password': 'पासवर्ड',
    'confirm_password': 'पासवर्ड की पुष्टि करें',
    'processing': 'प्रसंस्करण जारी है...',
    'passwords_do_not_match': 'पासवर्ड मेल नहीं खाते',
    'password_min_length': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
    'email_gmail_required': 'ईमेल एक मान्य जीमेल पता होना चाहिए जो @gmail.com से समाप्त हो',
    'select_your_role': 'अपनी भूमिका चुनें',
    'signup_as_user': 'उपयोगकर्ता के रूप में साइन अप करें',
    'user_role_description': 'रसीद डेटा का उपयोग करके माइक्रो-ऋण के लिए आवेदन करें',
    'signup_as_banker': 'बैंकर के रूप में साइन अप करें',
    'banker_role_description': 'ऋण आवेदनों की समीक्षा करें और उपयोगकर्ताओं का प्रबंधन करें',
    'signup_as_admin': 'व्यवस्थापक के रूप में साइन अप करें',
    'admin_role_description': 'प्लेटफ़ॉर्म और उपयोगकर्ता खातों का प्रबंधन करें',
    'select_role_to_continue': 'जारी रखने के लिए भूमिका चुनें',
    'no_role_selected': 'कोई भूमिका चयनित नहीं',
    'selected_role': 'चयनित भूमिका',
    'change': 'बदलें',
    'user': 'उपयोगकर्ता',
    'banker': 'बैंकर',
    'admin': 'व्यवस्थापक',
    'dont_have_account': 'खाता नहीं है?',
    'already_have_account': 'पहले से ही एक खाता है?',
    'username': 'उपयोगकर्ता नाम',
    'email': 'ईमेल',
    'back': 'वापस',
    
    // Notification System
    'just_now': 'अभी',
    'minutes_ago': '{minutes}म पहले',
    'hours_ago': '{hours}घ पहले',
    'days_ago': '{days}द पहले',
    'loan_approved': 'ऋण स्वीकृत',
    'loan_application_approved': '{amount} के लिए आपका ऋण आवेदन स्वीकृत कर लिया गया है।',
    'payment_due': 'भुगतान की तिथि',
    'payment_due_message': '{amount} का आपका ऋण भुगतान 3 दिनों में नियत है।',
    'payment_received': 'भुगतान प्राप्त',
    'payment_received_message': 'हमें आपका {amount} का ऋण भुगतान प्राप्त हो गया है।',
    'loan_disbursed': 'ऋण वितरित',
    'loan_disbursed_message': 'आपका {amount} का ऋण आपके खाते में वितरित कर दिया गया है।',
    
    // Banker Dashboard
    'banker_dashboard': 'बैंकर डैशबोर्ड',
    'all_users': 'सभी उपयोगकर्ता',
    'user_profile': 'उपयोगकर्ता प्रोफ़ाइल',
    'name': 'नाम',
    'email': 'ईमेल',
    'phone': 'फ़ोन',
    'address': 'पता',
    'occupation': 'व्यवसाय',
    'role': 'भूमिका',
    'credit_score': 'क्रेडिट स्कोर',
    'credit_decision': 'क्रेडिट निर्णय',
    'loan_amount': 'ऋण राशि',
    'message': 'संदेश',
    'uploaded_documents': 'अपलोड किए गए दस्तावेज़',
    'no_documents_uploaded': 'कोई दस्तावेज़ अपलोड नहीं किए गए',
    'download': 'डाउनलोड',
    'back_to_users': 'उपयोगकर्ताओं पर वापस जाएँ',
    'documents': 'दस्तावेज़',
    'search_users': 'उपयोगकर्ताओं की खोज करें...',
    'all_scores': 'सभी स्कोर',
    'all_decisions': 'सभी निर्णय',
    'refresh': 'रीफ्रेश',
    'actions': 'क्रियाएँ',
    'view_details': 'विवरण देखें',
    'no_users_found': 'आपके मानदंडों के अनुरूप कोई उपयोगकर्ता नहीं मिला',
    'no_documents': 'कोई दस्तावेज़ नहीं',
    'score_justification': 'स्कोर का औचित्य',
    'clear_filters': 'फ़िल्टर साफ़ करें',
    'total_users': 'कुल उपयोगकर्ता',
    'filtered_users': 'फ़िल्टर किए गए उपयोगकर्ता',
    
    // Common terms
    'try_again': 'पुनः प्रयास करें',
    'view_full_result': 'पूर्ण परिणाम देखें',
    'minutes': 'मिनट',
    'rupees': '₹',
    
    // Credit Score Analysis
    'credit_score_analysis': 'क्रेडिट स्कोर विश्लेषण',
    'analysis_generated_on': 'विश्लेषण पर उत्पन्न',
    'score_range': 'स्कोर रेंज',
    'next_review': 'अगली समीक्षा',
    'days_30': '30 दिन',
    'score_justification': 'स्कोर का औचित्य',
    'detailed_analysis': 'विस्तृत विश्लेषण',
    'positive_factors': 'सकारात्मक कारक',
    'negative_factors': 'नकारात्मक कारक',
    'recommendations': 'अनुशंसाएँ',
    'maintain_regular_transactions': 'नियमित लेन-देन बनाए रखें',
    'maintain_regular_transactions_desc': 'उधारदाताओं के साथ विश्वास बनाने के लिए सुसंगत खर्च के पैटर्न बनाए रखें',
    'reduce_refunds_and_returns': 'रिफंड और रिटर्न कम करें',
    'reduce_refunds_and_returns_desc': 'अपनी वित्तीय विश्वसनीयता में सुधार के लिए लेन-देन के उल्टाव को कम करें',
    'build_consistent_spending_pattern': 'सुसंगत खर्च का पैटर्न बनाएँ',
    'build_consistent_spending_pattern_desc': 'वित्तीय स्थिरता को प्रदर्शित करने के लिए नियमित खर्च की आदतें बनाएँ',
    'excellent': 'उत्कृष्ट',
    'good': 'अच्छा',
    'fair': 'उचित',
    'poor': 'खराब',
    'no_data_available': 'विश्लेषण के लिए कोई डेटा उपलब्ध नहीं है',
    'your_spending_is_stable_but_savings_are_low': 'आपका खर्च स्थिर है लेकिन बचत कम है',
    'your_financial_behavior_is_consistent': 'आपका वित्तीय व्यवहार सुसंगत है',
    'your_financial_pattern_needs_improvement': 'आपके वित्तीय पैटर्न में सुधार की आवश्यकता है',
    'excellent_score_description': 'उत्कृष्ट क्रेडिट स्कोर मजबूत वित्तीय विश्वसनीयता और विश्वासयोग्यता को इंगित करता है',
    'good_score_description': 'अच्छा क्रेडिट स्कोर विश्वसनीय वित्तीय व्यवहार को दर्शाता है जिसमें मामूली सुधार की आवश्यकता होती है',
    'fair_score_description': 'उचित क्रेडिट स्कोर कुछ वित्तीय असंगतियों को सुझाता है जिन पर ध्यान देने की आवश्यकता है',
    'poor_score_description': 'खराब क्रेडिट स्कोर महत्वपूर्ण वित्तीय विश्वसनीयता समस्याओं को इंगित करता है',
    'copy_score': 'स्कोर कॉपी करें',
    'score_thresholds': 'स्कोर थ्रेशोल्ड्स',
    'approve': 'स्वीकृत करें',
    'approve_with_cap': 'कैप के साथ स्वीकृत करें',
    'review': 'समीक्षा',
    'reject': 'अस्वीकार करें',
    
    // Admin Dashboard
    'admin_dashboard': 'व्यवस्थापक डैशबोर्ड',
    'role': 'भूमिका',
    'created_at': 'निर्माण तिथि',
    'edit': 'संपादित करें',
    'save': 'सहेजें',
    'cancel': 'रद्द करें',
    'delete': 'हटाएँ',
    'confirm_delete_user': 'क्या आप वाकई इस उपयोगकर्ता को हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।',
    'user_profile': 'उपयोगकर्ता प्रोफ़ाइल',
    'username': 'उपयोगकर्ता नाम',
    'full_name': 'पूरा नाम',
  }
};

// Translation function
export const t = (key, language = 'en') => {
  // Default to English if language not supported
  const lang = translations[language] ? language : 'en';
  
  // Return translation if exists, otherwise return the key
  return translations[lang][key] || key;
};

export default translations;