// Localization dictionary
const translations = {
  en: {
    // Onboarding Screen
    'justifi': 'JustiFi',
    'instant_micro_loans': 'Instant Micro-Loans Using Receipts',
    'get_approved': 'Get approved in minutes without CIBIL or PAN',
    'decision_time': 'Decision in under 5 minutes',
    'no_pan_required': 'No PAN/Aadhaar required',
    'loan_amount': 'Loans up to ₹10,000',
    'get_started': 'Get Started',
    'terms_consent': 'By continuing, you agree to our Terms of Service and Privacy Policy',
    
    // Upload Screen
    'upload_documents': 'Upload Your Documents',
    'upload_salary_receipt': 'Upload Your Salary Receipt',
    'upload_salary_receipt_description': 'Share your salary receipt to help calculate your credit score',
    'upload_bank_statement': 'Upload Your Bank Statement',
    'upload_bank_statement_description': 'Share your bank statement to help calculate your credit score',
    'choose_salary_receipt': 'Choose Salary Receipt',
    'choose_bank_statement': 'Choose Bank Statement',
    'upload_salary_receipt_button': 'Upload Salary Receipt',
    'upload_bank_statement_button': 'Upload Bank Statement',
    'salary_receipt_uploaded_successfully': 'Salary receipt uploaded successfully!',
    'bank_statement_uploaded_successfully': 'Bank statement uploaded successfully!',
    'please_upload_at_least_one_document': 'Please upload at least one document',
    'drag_drop_receipts': 'Drag & drop your receipt files here',
    'or': 'or',
    'choose_files': 'Choose Files',
    'selected': 'Selected',
    'or_try_demo': 'Or try with demo data:',
    'use_demo_data': 'Use Demo Data',
    'processing': 'Processing...',
    'calculate_my_score': 'Calculate My Score',
    'no_pan_aadhaar_required': 'No PAN/Aadhaar required. Your data is encrypted and secure.',
    'please_select_file': 'Please select a file first',
    'error_processing_request': 'Error processing your request. Please try again.',
    'please_select_demo_user': 'Please select a demo user',
    
    // Result Screen
    'your_credit_assessment': 'Your Credit Assessment',
    'trust_score': 'TrustScore',
    'top_reasons': 'Top Reasons',
    'loan_offer': 'Loan Offer',
    'available_for_disbursement': 'Available for immediate disbursement',
    'accept_loan': 'Accept Loan',
    'loan_disbursed_success': 'Loan of ₹{amount} has been successfully disbursed!',
    'failed_to_disburse_loan': 'Failed to disburse loan',
    'loan_approved': 'Loan Approved!',
    'error': 'Error',
    'transaction_id': 'Transaction ID',
    'amount': 'Amount',
    'view_profile': 'View Profile',
    'loan_history': 'Loan History',
    'spending_patterns': 'Spending Patterns',
    'settings': 'Settings',
    'assess_another_person': 'Assess Another Person',
    'data_protected': 'Your data is protected. We only use it for credit assessment.',
    'approved': 'Approved',
    'approved_with_cap': 'Approved with Cap',
    'under_review': 'Under Review',
    'rejected': 'Rejected',
    'pending': 'Pending',
    'loading': 'Loading',
    'hundred': '100',
    
    // Profile Screen
    'user_profile': 'User Profile',
    'user': 'User',
    'user_initial': 'U',
    'email': 'Email',
    'phone': 'Phone',
    'address': 'Address',
    'occupation': 'Occupation',
    'not_provided': 'Not provided',
    'edit_profile': 'Edit Profile',
    'upload_document': 'Upload Document',
    'view_notifications': 'Notifications',
    'view_loan_history': 'View Loan History',
    'view_spending_patterns': 'View Spending Patterns',
    'app_settings': 'App Settings',
    'logout': 'Logout',
    'mark_all_as_read': 'Mark All as Read',
    'no_notifications': 'No notifications',
    'unread': 'Unread',
    'full_name': 'Full Name',
    'enter_full_name': 'Enter your full name',
    'enter_email': 'Enter your email',
    'enter_phone_number': 'Enter your phone number',
    'enter_address': 'Enter your address',
    'enter_occupation': 'Enter your occupation',
    'cancel': 'Cancel',
    'save_changes': 'Save Changes',
    'back': 'Back',
    'notifications_feature_coming_soon': 'Notifications feature is coming soon!',
    
    // Loan History Screen
    'loading_loan_history': 'Loading loan history',
    'no_loan_history_found': 'No loan history found',
    'disbursed': 'Disbursed',
    'repaid': 'Repaid',
    'repayment_due': 'Repayment Due',
    
    // Spending Patterns Screen
    'spending_patterns_title': 'Spending Patterns',
    'loading_spending_patterns': 'Loading spending patterns',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'spending_by_category': 'Spending by Category',
    'spending_summary': 'Spending Summary',
    'groceries': 'Groceries',
    'transport': 'Transport',
    'entertainment': 'Entertainment',
    'utilities': 'Utilities',
    'dining': 'Dining',
    'other': 'Other',
    'rent': 'Rent',
    'user_diary': 'User Diary',
    'add_financial_note': 'Add a financial note or activity...',
    'add_entry': 'Add Entry',
    'delete': 'Delete',
    'no_diary_entries': 'No diary entries yet. Add your first financial note!',
    
    // Settings Screen
    'notifications': 'Notifications',
    'enable_notifications': 'Enable Notifications',
    'email_notifications': 'Email Notifications',
    'sms_notifications': 'SMS Notifications',
    'appearance': 'Appearance',
    'dark_mode': 'Dark Mode',
    'view_mode': 'View Mode',
    'mobile_view': 'Mobile View',
    'desktop_view': 'Desktop View',
    'preferences': 'Preferences',
    'language': 'Language',
    'currency': 'Currency',
    'english': 'English',
    'hindi': 'Hindi',
    'tamil': 'Tamil',
    'telugu': 'Telugu',
    'kannada': 'Kannada',
    'indian_rupee': 'Indian Rupee (₹)',
    'us_dollar': 'US Dollar ($)',
    'euro': 'Euro (€)',
    'reset_to_default': 'Reset to Default',
    'save_settings': 'Save Settings',
    'settings_saved_successfully': 'Settings saved successfully!',
    
    // Login/Signup Screen
    'login': 'Login',
    'signup': 'Sign Up',
    'username': 'Username',
    'email_or_username': 'Email or Username',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'passwords_do_not_match': 'Passwords do not match',
    'dont_have_account': 'Don\'t have an account?',
    'already_have_account': 'Already have an account?',
    
    // Notification System
    'just_now': 'Just now',
    'minutes_ago': '{minutes}m ago',
    'hours_ago': '{hours}h ago',
    'days_ago': '{days}d ago',
    'loan_approved': 'Loan Approved',
    'loan_application_approved': 'Your loan application for {amount} has been approved.',
    'payment_due': 'Payment Due',
    'payment_due_message': 'Your loan payment of {amount} is due in 3 days.',
    'payment_received': 'Payment Received',
    'payment_received_message': 'We have received your loan payment of {amount}.',
    'loan_disbursed': 'Loan Disbursed',
    'loan_disbursed_message': 'Your loan of {amount} has been disbursed to your account.',
    
    // Common terms
    'try_again': 'Try Again',
    
    // Demo Users
    'rani': 'Rani',
    'amit': 'Amit',
    'priya': 'Priya',
    'low_risk': 'Low Risk',
    'medium_risk': 'Medium Risk',
    'high_risk': 'High Risk',
    
    // Common terms
    'minutes': 'minutes',
    'rupees': '₹',
  },
  hi: {
    // Onboarding Screen
    'justifi': 'जस्टिफाई',
    'instant_micro_loans': 'रसीद का उपयोग करके तुरंत माइक्रो-ऋण',
    'get_approved': 'CIBIL या PAN के बिना मिनटों में स्वीकृति प्राप्त करें',
    'decision_time': '5 मिनट से भी कम समय में निर्णय',
    'no_pan_required': 'PAN/आधार की आवश्यकता नहीं है',
    'loan_amount': '₹10,000 तक के ऋण',
    'get_started': 'शुरू करें',
    'terms_consent': 'जारी रखकर, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत होते हैं',
    
    // Upload Screen
    'upload_documents': 'अपने दस्तावेज़ अपलोड करें',
    'upload_salary_receipt': 'अपनी वेतन रसीद अपलोड करें',
    'upload_salary_receipt_description': 'अपना क्रेडिट स्कोर गणना करने में मदद के लिए अपनी वेतन रसीद साझा करें',
    'upload_bank_statement': 'अपना बैंक स्टेटमेंट अपलोड करें',
    'upload_bank_statement_description': 'अपना क्रेडिट स्कोर गणना करने में मदद के लिए अपना बैंक स्टेटमेंट साझा करें',
    'choose_salary_receipt': 'वेतन रसीद चुनें',
    'choose_bank_statement': 'बैंक स्टेटमेंट चुनें',
    'upload_salary_receipt_button': 'वेतन रसीद अपलोड करें',
    'upload_bank_statement_button': 'बैंक स्टेटमेंट अपलोड करें',
    'salary_receipt_uploaded_successfully': 'वेतन रसीद सफलतापूर्वक अपलोड कर दी गई!',
    'bank_statement_uploaded_successfully': 'बैंक स्टेटमेंट सफलतापूर्वक अपलोड कर दिया गया!',
    'please_upload_at_least_one_document': 'कृपया कम से कम एक दस्तावेज़ अपलोड करें',
    'drag_drop_receipts': 'अपनी रसीद फ़ाइलों को यहाँ ड्रैग एंड ड्रॉप करें',
    'or': 'या',
    'choose_files': 'फ़ाइलें चुनें',
    'selected': 'चयनित',
    'or_try_demo': 'या डेमो डेटा के साथ प्रयास करें:',
    'use_demo_data': 'डेमो डेटा का उपयोग करें',
    'processing': 'प्रसंस्करण जारी है...',
    'calculate_my_score': 'मेरा स्कोर गणना करें',
    'no_pan_aadhaar_required': 'PAN/आधार की आवश्यकता नहीं है। आपका डेटा एन्क्रिप्टेड और सुरक्षित है।',
    'please_select_file': 'कृपया पहले एक फ़ाइल चुनें',
    'error_processing_request': 'आपके अनुरोध को संसाधित करने में त्रुटि। कृपया पुन: प्रयास करें।',
    'please_select_demo_user': 'कृपया एक डेमो उपयोगकर्ता चुनें',
    
    // Result Screen
    'your_credit_assessment': 'आपका क्रेडिट मूल्यांकन',
    'trust_score': 'ट्रस्टस्कोर',
    'top_reasons': 'शीर्ष कारण',
    'loan_offer': 'ऋण प्रस्ताव',
    'available_for_disbursement': 'तत्काल वितरण के लिए उपलब्ध',
    'accept_loan': 'ऋण स्वीकार करें',
    'loan_disbursed_success': '₹{amount} का ऋण सफलतापूर्वक वितरित कर दिया गया है!',
    'failed_to_disburse_loan': 'ऋण वितरित करने में विफल',
    'loan_approved': 'ऋण स्वीकृत!',
    'error': 'त्रुटि',
    'transaction_id': 'लेन-देन आईडी',
    'amount': 'राशि',
    'view_profile': 'प्रोफ़ाइल देखें',
    'loan_history': 'ऋण इतिहास',
    'spending_patterns': 'खर्च के पैटर्न',
    'settings': 'सेटिंग्स',
    'assess_another_person': 'दूसरे व्यक्ति का मूल्यांकन करें',
    'data_protected': 'आपका डेटा सुरक्षित है। हम इसका उपयोग केवल क्रेडिट मूल्यांकन के लिए करते हैं।',
    'approved': 'स्वीकृत',
    'approved_with_cap': 'कैप के साथ स्वीकृत',
    'under_review': 'समीक्षा में',
    'rejected': 'अस्वीकृत',
    'pending': 'लंबित',
    'loading': 'लोड हो रहा है',
    'hundred': '100',
    
    // Profile Screen
    'user_profile': 'उपयोगकर्ता प्रोफ़ाइल',
    'user': 'उपयोगकर्ता',
    'user_initial': 'उ',
    'email': 'ईमेल',
    'phone': 'फ़ोन',
    'address': 'पता',
    'occupation': 'व्यवसाय',
    'not_provided': 'प्रदान नहीं किया गया',
    'edit_profile': 'प्रोफ़ाइल संपादित करें',
    'upload_document': 'दस्तावेज़ अपलोड करें',
    'view_notifications': 'सूचनाएँ',
    'view_loan_history': 'ऋण इतिहास देखें',
    'view_spending_patterns': 'खर्च के पैटर्न देखें',
    'app_settings': 'ऐप सेटिंग्स',
    'logout': 'लॉग आउट',
    'mark_all_as_read': 'सभी को पढ़ा हुआ चिह्नित करें',
    'no_notifications': 'कोई सूचनाएँ नहीं',
    'unread': 'अपठित',
    'full_name': 'पूरा नाम',
    'enter_full_name': 'अपना पूरा नाम दर्ज करें',
    'enter_email': 'अपना ईमेल दर्ज करें',
    'enter_phone_number': 'अपना फ़ोन नंबर दर्ज करें',
    'enter_address': 'अपना पता दर्ज करें',
    'enter_occupation': 'अपना व्यवसाय दर्ज करें',
    'cancel': 'रद्द करें',
    'save_changes': 'परिवर्तन सहेजें',
    'back': 'वापस',
    'notifications_feature_coming_soon': 'सूचनाएँ सुविधा जल्द आ रही है!',
    
    // Loan History Screen
    'loading_loan_history': 'ऋण इतिहास लोड हो रहा है',
    'no_loan_history_found': 'कोई ऋण इतिहास नहीं मिला',
    'disbursed': 'वितरित',
    'repaid': 'चुका दिया गया',
    'repayment_due': 'पुनर्भुगतान की तिथि',
    
    // Spending Patterns Screen
    'spending_patterns_title': 'खर्च के पैटर्न',
    'loading_spending_patterns': 'खर्च के पैटर्न लोड हो रहे हैं',
    'daily': 'दैनिक',
    'weekly': 'साप्ताहिक',
    'monthly': 'मासिक',
    'spending_by_category': 'श्रेणी के अनुसार खर्च',
    'spending_summary': 'खर्च का सारांश',
    'groceries': 'किराने का सामान',
    'transport': 'परिवहन',
    'entertainment': 'मनोरंजन',
    'utilities': 'उपयोगिताएँ',
    'dining': 'भोजन',
    'other': 'अन्य',
    'rent': 'किराया',
    'user_diary': 'उपयोगकर्ता डायरी',
    'add_financial_note': 'एक वित्तीय नोट या गतिविधि जोड़ें...',
    'add_entry': 'प्रविष्टि जोड़ें',
    'delete': 'हटाएँ',
    'no_diary_entries': 'अभी तक कोई डायरी प्रविष्टि नहीं है। अपना पहला वित्तीय नोट जोड़ें!',
    
    // Settings Screen
    'notifications': 'सूचनाएँ',
    'enable_notifications': 'सूचनाएँ सक्षम करें',
    'email_notifications': 'ईमेल सूचनाएँ',
    'sms_notifications': 'एसएमएस सूचनाएँ',
    'appearance': 'उपस्थिति',
    'dark_mode': 'डार्क मोड',
    'view_mode': 'दृश्य मोड',
    'mobile_view': 'मोबाइल दृश्य',
    'desktop_view': 'डेस्क्टॉप दृश्य',
    'preferences': 'प्राथमिकताएँ',
    'language': 'भाषा',
    'currency': 'मुद्रा',
    'english': 'अंग्रेज़ी',
    'hindi': 'हिंदी',
    'tamil': 'तमिल',
    'telugu': 'तेलुगू',
    'kannada': 'कन्नड़',
    'indian_rupee': 'भारतीय रुपया (₹)',
    'us_dollar': 'अमेरिकी डॉलर ($)',
    'euro': 'यूरो (€)',
    'reset_to_default': 'डिफ़ॉल्ट पर रीसेट करें',
    'save_settings': 'सेटिंग्स सहेजें',
    'settings_saved_successfully': 'सेटिंग्स सफलतापूर्वक सहेजी गईं!',
    
    // Login/Signup Screen
    'login': 'लॉग इन करें',
    'signup': 'साइन अप करें',
    'username': 'उपयोगकर्ता नाम',
    'email_or_username': 'ईमेल या उपयोगकर्ता नाम',
    'password': 'पासवर्ड',
    'confirm_password': 'पासवर्ड की पुष्टि करें',
    'passwords_do_not_match': 'पासवर्ड मेल नहीं खाते',
    'dont_have_account': 'क्या आपके पास खाता नहीं है?',
    'already_have_account': 'क्या आपके पास पहले से एक खाता है?',
    
    // Notification System
    'just_now': 'अभी',
    'minutes_ago': '{minutes} मिनट पहले',
    'hours_ago': '{hours} घंटे पहले',
    'days_ago': '{days} दिन पहले',
    'loan_approved': 'ऋण स्वीकृत',
    'loan_application_approved': 'आपका ₹{amount} के लिए ऋण आवेदन स्वीकृत कर लिया गया है।',
    'payment_due': 'भुगतान की तिथि',
    'payment_due_message': 'आपका ₹{amount} का ऋण भुगतान 3 दिनों में नियत है।',
    'payment_received': 'भुगतान प्राप्त',
    'payment_received_message': 'हमें आपका ₹{amount} का ऋण भुगतान प्राप्त हो गया है।',
    'loan_disbursed': 'ऋण वितरित',
    'loan_disbursed_message': 'आपका ₹{amount} का ऋण आपके खाते में वितरित कर दिया गया है।',
    
    // Common terms
    'try_again': 'पुनः प्रयास करें',
    
    // Demo Users
    'rani': 'रानी',
    'amit': 'अमित',
    'priya': 'प्रिया',
    'low_risk': 'कम जोखिम',
    'medium_risk': 'मध्यम जोखिम',
    'high_risk': 'उच्च जोखिम',
    
    // Common terms
    'minutes': 'मिनट',
    'rupees': '₹',
  },
  ta: {
    // Onboarding Screen
    'justifi': 'ஜஸ்டிஃபி',
    'instant_micro_loans': 'ரசீதுகளைப் பயன்படுத்தி உடனடி மைக்ரோ-கடன்கள்',
    'get_approved': 'CIBIL அல்லாமல் நிமிடங்களில் அங்கீகரிக்கப்படுவீர்கள்',
    'decision_time': '5 நிமிடங்களுக்குள் முடிவு',
    'no_pan_required': 'PAN/ஆதார் தேவையில்லை',
    'loan_amount': '₹10,000 வரை கடன்கள்',
    'get_started': 'தொடங்குங்கள்',
    'terms_consent': 'தொடருவதன் மூலம், எங்கள் சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்கிறீர்கள்',
    
    // Upload Screen
    'upload_documents': 'உங்கள் ஆவணங்களை பதிவேற்றவும்',
    'upload_salary_receipt': 'உங்கள் சம்பள ரசீதை பதிவேற்றவும்',
    'upload_salary_receipt_description': 'உங்கள் கடன் ஸ்கோரை கணக்கிட உதவ உங்கள் சம்பள ரசீதை பகிர்ந்து கொள்ளுங்கள்',
    'upload_bank_statement': 'உங்கள் வங்கி அறிக்கையை பதிவேற்றவும்',
    'upload_bank_statement_description': 'உங்கள் கடன் ஸ்கோரை கணக்கிட உதவ உங்கள் வங்கி அறிக்கையை பகிர்ந்து கொள்ளுங்கள்',
    'choose_salary_receipt': 'சம்பள ரசீதைத் தேர்ந்தெடுக்கவும்',
    'choose_bank_statement': 'வங்கி அறிக்கையைத் தேர்ந்தெடுக்கவும்',
    'upload_salary_receipt_button': 'சம்பள ரசீதை பதிவேற்றவும்',
    'upload_bank_statement_button': 'வங்கி அறிக்கையை பதிவேற்றவும்',
    'salary_receipt_uploaded_successfully': 'சம்பள ரசீது வெற்றிகரமாக பதிவேற்றப்பட்டது!',
    'bank_statement_uploaded_successfully': 'வங்கி அறிக்கை வெற்றிகரமாக பதிவேற்றப்பட்டது!',
    'please_upload_at_least_one_document': 'குறைந்தது ஒரு ஆவணத்தையாவது பதிவேற்றவும்',
    'drag_drop_receipts': 'உங்கள் ரசீது கோப்புகளை இங்கே இழுத்து விடவும்',
    'or': 'அல்லது',
    'choose_files': 'கோப்புகளைத் தேர்ந்தெடுக்கவும்',
    'selected': 'தேர்ந்தெடுக்பட்டது',
    'or_try_demo': 'அல்லது டெமோ தரவுடன் முயற்சிக்கவும்:',
    'use_demo_data': 'டெமோ தரவைப் பயன்படுத்தவும்',
    'processing': 'செயலாக்கம்...',
    'calculate_my_score': 'எனது ஸ்கோரை கணக்கிடு',
    'no_pan_aadhaar_required': 'PAN/ஆதார் தேவையில்லை. உங்கள் தரவு மறைகுறியாக்கம் செய்யப்பட்டு பாதுகாப்பாக உள்ளது.',
    'please_select_file': 'முதலில் ஒரு கோப்பைத் தேர்ந்தெடுக்கவும்',
    'error_processing_request': 'உங்கள் கோரிக்கையை செயலாக்குவதில் பிழை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    'please_select_demo_user': 'ஒரு டெமோ பயனரைத் தேர்ந்தெடுக்கவும்',
    
    // Result Screen
    'your_credit_assessment': 'உங்கள் கடன் மதிப்பீடு',
    'trust_score': 'ட்ரஸ்ட்ஸ்கோர்',
    'top_reasons': 'முக்கிய காரணங்கள்',
    'loan_offer': 'கடன் வாய்ப்பு',
    'available_for_disbursement': 'உடனடி விநியோகத்திற்கு கிடைக்கிறது',
    'accept_loan': 'கடனை ஏற்கவும்',
    'loan_disbursed_success': '₹{amount} கடன் வெற்றிகரமாக வழங்கப்பட்டது!',
    'failed_to_disburse_loan': 'கடனை வழங்க முடியவில்லை',
    'loan_approved': 'கடன் அங்கீகரிக்கப்பட்டது!',
    'error': 'பிழை',
    'transaction_id': 'பரிவர்த்தனை ஐடி',
    'amount': 'தொகை',
    'view_profile': 'சுயவிவரத்தை பார்க்கவும்',
    'loan_history': 'கடன் வரலாறு',
    'spending_patterns': 'செலவு முறைகள்',
    'settings': 'அமைப்புகள்',
    'assess_another_person': 'மற்றொரு நபரை மதிப்பீடு செய்யவும்',
    'data_protected': 'உங்கள் தரவு பாதுகாக்கப்பட்டுள்ளது. கடன் மதிப்பீட்டிற்கு மட்டுமே பயன்படுத்தப்படுகிறது.',
    'approved': 'அங்கீகரிக்கப்பட்டது',
    'approved_with_cap': 'கேப்புடன் அங்கீகரிக்கப்பட்டது',
    'under_review': 'மதிப்பாய்வில்',
    'rejected': 'நிராகரிக்கப்பட்டது',
    'pending': 'நிலுவையில்',
    'loading': 'ஏற்றுகிறது',
    'hundred': '100',
    
    // Profile Screen
    'user_profile': 'பயனர் சுயவிவரம்',
    'user': 'பயனர்',
    'user_initial': 'ப',
    'email': 'மின்னஞ்சல்',
    'phone': 'தொலைபேசி',
    'address': 'முகவரி',
    'occupation': 'தொழில்',
    'not_provided': 'வழங்கப்படவில்லை',
    'edit_profile': 'சுயவிவரத்தை திருத்தவும்',
    'upload_document': 'ஆவணத்தை பதிவேற்றவும்',
    'view_notifications': 'அறிவிப்புகள்',
    'view_loan_history': 'கடன் வரலாற்றை பார்க்கவும்',
    'view_spending_patterns': 'செலவு முறைகளை பார்க்கவும்',
    'app_settings': 'செயலிக்கான அமைப்புகள்',
    'logout': 'வெளியேறு',
    'mark_all_as_read': 'அனைத்தையும் வாசித்ததாக குறிக்கவும்',
    'no_notifications': 'அறிவிப்புகள் எதுவுமில்லை',
    'unread': 'படிக்காதது',
    'full_name': 'முழு பெயர்',
    'enter_full_name': 'உங்கள் முழு பெயரை உள்ளிடவும்',
    'enter_email': 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    'enter_phone_number': 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
    'enter_address': 'உங்கள் முகவரியை உள்ளிடவும்',
    'enter_occupation': 'உங்கள் தொழிலை உள்ளிடவும்',
    'cancel': 'ரத்து செய்',
    'save_changes': 'மாற்றங்களை சேமி',
    'back': 'மீண்டும்',
    'notifications_feature_coming_soon': 'அறிவிப்புகள் விளைவுகிறது!',
    
    // Loan History Screen
    'loading_loan_history': 'கடன் வரலாறு ஏற்றப்படுகிறது',
    'no_loan_history_found': 'கடன் வரலாறு எதுவும் கிடைக்கவில்லை',
    'disbursed': 'வழங்கப்பட்டது',
    'repaid': 'மீள் செலுத்தப்பட்டது',
    'repayment_due': 'மீள் செலுத்த வேண்டியது',
    
    // Spending Patterns Screen
    'spending_patterns_title': 'செலவு முறைகள்',
    'loading_spending_patterns': 'செலவு முறைகள் ஏற்றப்படுகின்றன',
    'daily': 'தினசரி',
    'weekly': 'வாரந்தோறும்',
    'monthly': 'மாதந்தோறும்',
    'spending_by_category': 'வகைப்படி செலவு',
    'spending_summary': 'செலவு சுருக்கம்',
    'groceries': 'கிராசரிகள்',
    'transport': 'போக்குவரத்து',
    'entertainment': 'பொழுதுபோக்கு',
    'utilities': 'சேவைகள்',
    'dining': 'உணவு',
    'other': 'மற்றவை',
    'rent': 'வாடகை',
    'user_diary': 'பயனர் குறிப்பேடு',
    'add_financial_note': 'ஒரு நிதிக் குறிப்பை அல்லது செயல்பாட்டைச் சேர்க்கவும்...',
    'add_entry': 'உள்ளீட்டைச் சேர்க்கவும்',
    'delete': 'அழி',
    'no_diary_entries': 'இதுவரை குறிப்பேட்டு உள்ளீடுகள் எதுவும் இல்லை. உங்கள் முதல் நிதிக் குறிப்பைச் சேர்க்கவும்!',
    
    // Settings Screen
    'notifications': 'அறிவிப்புகள்',
    'enable_notifications': 'அறிவிப்புகளை இயக்கவும்',
    'email_notifications': 'மின்னஞ்சல் அறிவிப்புகள்',
    'sms_notifications': 'SMS அறிவிப்புகள்',
    'appearance': 'தோற்றம்',
    'dark_mode': 'இருண்ட பயன்முறை',
    'view_mode': 'காட்சி முறை',
    'mobile_view': 'மொபைல் காட்சி',
    'desktop_view': 'டெஸ்க்டாப் காட்சி',
    'preferences': 'விருப்பத்தேர்வுகள்',
    'language': 'மொழி',
    'currency': 'நாணயம்',
    'english': 'ஆங்கிலம்',
    'hindi': 'ஹிந்தி',
    'tamil': 'தமிழ்',
    'telugu': 'தெலுங்கு',
    'kannada': 'கன்னடம்',
    'indian_rupee': 'இந்திய ரூபாய் (₹)',
    'us_dollar': 'அமெரிக்க டாலர் ($)',
    'euro': 'யூரோ (€)',
    'reset_to_default': 'இயல்புநிலைக்கு மீட்டமை',
    'save_settings': 'அமைப்புகளை சேமி',
    'settings_saved_successfully': 'அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டது!',
    
    // Login/Signup Screen
    'login': 'உள்நுழைக',
    'signup': 'பதிவு செய்யவும்',
    'username': 'பயனர்பெயர்',
    'email_or_username': 'மின்னஞ்சல் அல்லது பயனர்பெயர்',
    'password': 'கடவுச்சொல்',
    'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'passwords_do_not_match': 'கடவுச்சொற்கள் பொருந்தவில்லை',
    'dont_have_account': 'கணக்கு இல்லையா?',
    'already_have_account': 'ஏற்கனவே ஒரு கணக்கு உள்ளதா?',
    
    // Notification System
    'just_now': 'இப்போது',
    'minutes_ago': '{minutes} நிமிடங்களுக்கு முன்',
    'hours_ago': '{hours} மணி நேரம் முன்',
    'days_ago': '{days} நாட்களுக்கு முன்',
    'loan_approved': 'கடன் அங்கீகரிக்கப்பட்டது',
    'loan_application_approved': 'உங்கள் ₹{amount}க்கான கடன் விண்ணப்பம் அங்கீகரிக்கப்பட்டது.',
    'payment_due': 'செலுத்த வேண்டியது',
    'payment_due_message': 'உங்கள் ₹{amount} கடன் கொடுப்பனவு 3 நாட்களில் நிலுவையில் உள்ளது.',
    'payment_received': 'கொடுப்பனவு பெறப்பட்டது',
    'payment_received_message': 'உங்கள் ₹{amount} கடன் கொடுப்பனவை நாங்கள் பெற்றுள்ளோம்.',
    'loan_disbursed': 'கடன் வழங்கப்பட்டது',
    'loan_disbursed_message': 'உங்கள் ₹{amount} கடன் உங்கள் கணக்கில் வழங்கப்பட்டுள்ளது.',
    
    // Common terms
    'try_again': 'மீண்டும் முயற்சிக்கவும்',
    
    // Demo Users
    'rani': 'ராணி',
    'amit': 'அமித்',
    'priya': 'பிரியா',
    'low_risk': 'குறைந்த ஆபத்து',
    'medium_risk': 'நடுத்தர ஆபத்து',
    'high_risk': 'அதிக ஆபத்து',
    
    // Common terms
    'minutes': 'நிமிடங்கள்',
    'rupees': '₹',
  },
  te: {
    // Onboarding Screen
    'justifi': 'జస్టిఫి',
    'instant_micro_loans': 'రసీదులను ఉపయోగించి వెంటనే మైక్రో-లోన్లు',
    'get_approved': 'CIBIL లేదా PAN అవసరం లేకుండా నిమిషాల్లో ఆమోదం పొందండి',
    'decision_time': '5 నిమిషాల లోపు నిర్ణయం',
    'no_pan_required': 'PAN/ఆధార్ అవసరం లేదు',
    'loan_amount': '₹10,000 వరకు రుణాలు',
    'get_started': 'ప్రారంభించండి',
    'terms_consent': 'కొనసాగడం ద్వారా, మీరు మా సేవా నిబంధనలు మరియు గోప్యతా విధానానికి అంగీకరిస్తున్నారు',
    
    // Upload Screen
    'upload_documents': 'మీ పత్రాలను అప్లోడ్ చేయండి',
    'upload_salary_receipt': 'మీ జీతపు రసీదును అప్లోడ్ చేయండి',
    'upload_salary_receipt_description': 'మీ క్రెడిట్ స్కోర్ లెక్కించడంలో సహాయం కోసం మీ జీతపు రసీదును పంచుకోండి',
    'upload_bank_statement': 'మీ బ్యాంకు స్టేట్‌మెంట్‌ను అప్లోడ్ చేయండి',
    'upload_bank_statement_description': 'మీ క్రెడిట్ స్కోర్ లెక్కించడంలో సహాయం కోసం మీ బ్యాంకు స్టేట్‌మెంట్‌ను పంచుకోండి',
    'choose_salary_receipt': 'జీతపు రసీదును ఎంచుకోండి',
    'choose_bank_statement': 'బ్యాంకు స్టేట్‌మెంట్‌ను ఎంచుకోండి',
    'upload_salary_receipt_button': 'జీతపు రసీదును అప్లోడ్ చేయండి',
    'upload_bank_statement_button': 'బ్యాంకు స్టేట్‌మెంట్‌ను అప్లోడ్ చేయండి',
    'salary_receipt_uploaded_successfully': 'జీతపు రసీదు విజయవంతంగా అప్లోడ్ చేయబడింది!',
    'bank_statement_uploaded_successfully': 'బ్యాంకు స్టేట్‌మెంట్ విజయవంతంగా అప్లోడ్ చేయబడింది!',
    'please_upload_at_least_one_document': 'దయచేసి కనీసం ఒక పత్రం అప్లోడ్ చేయండి',
    'drag_drop_receipts': 'మీ రసీదు ఫైల్స్ ను ఇక్కడ డ్రాగ్ అండ్ డ్రాప్ చేయండి',
    'or': 'లేదా',
    'choose_files': 'ఫైల్స్ ను ఎంచుకోండి',
    'selected': 'ఎంచుకోబడింది',
    'or_try_demo': 'లేదా డెమో డేటాతో ప్రయత్నించండి:',
    'use_demo_data': 'డెమో డేటాను ఉపయోగించండి',
    'processing': 'ప్రాసెస్ అవుతోంది...',
    'calculate_my_score': 'నా స్కోర్ లెక్కించండి',
    'no_pan_aadhaar_required': 'PAN/ఆధార్ అవసరం లేదు. మీ డేటా ఎన్క్రిప్ట్ అయి భద్రపరచబడింది.',
    'please_select_file': 'దయచేసి ముందుగా ఒక ఫైల్ ను ఎంచుకోండి',
    'error_processing_request': 'మీ అభ్యర్థనను ప్రాసెస్ చేయడంలో లోపం. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    'please_select_demo_user': 'దయచేసి ఒక డెమో వినియోగదారుని ఎంచుకోండి',
    
    // Result Screen
    'your_credit_assessment': 'మీ క్రెడిట్ అసెస్మెంట్',
    'trust_score': 'ట్రస్ట్‌స్కోర్',
    'top_reasons': 'ప్రధాన కారణాలు',
    'loan_offer': 'లోన్ ఆఫర్',
    'available_for_disbursement': 'వెంటనే డిస్బర్స్మెంట్ కోసం అందుబాటులో',
    'accept_loan': 'లోన్ ను అంగీకరించండి',
    'loan_disbursed_success': '₹{amount} లోన్ విజయవంతంగా డిస్బర్స్ చేయబడింది!',
    'failed_to_disburse_loan': 'లోన్ డిస్బర్స్ చేయడంలో విఫలం',
    'loan_approved': 'లోన్ ఆమోదించబడింది!',
    'error': 'లోపం',
    'transaction_id': 'ట్రాన్సాక్షన్ ఐడి',
    'amount': 'మొత్తం',
    'view_profile': 'ప్రొఫైల్ చూడండి',
    'loan_history': 'లోన్ చరిత్ర',
    'spending_patterns': 'ఖర్చు ప్యాటర్న్లు',
    'settings': 'సెట్టింగ్స్',
    'assess_another_person': 'మరొకరిని అసెస్ చేయండి',
    'data_protected': 'మీ డేటా రక్షించబడింది. క్రెడిట్ అసెస్మెంట్ కోసమే ఉపయోగిస్తాము.',
    'approved': 'ఆమోదించబడింది',
    'approved_with_cap': 'క్యాప్ తో ఆమోదించబడింది',
    'under_review': 'సమీక్షలో ఉంది',
    'rejected': 'తిరస్కరించబడింది',
    'pending': 'పెండింగ్',
    'loading': 'లోడవుతోంది',
    'hundred': '100',
    
    // Profile Screen
    'user_profile': 'వినియోగదారు ప్రొఫైల్',
    'user': 'వినియోగదారు',
    'user_initial': 'వి',
    'email': 'ఇమెయిల్',
    'phone': 'ఫోన్',
    'address': 'చిరునామా',
    'occupation': 'వృత్తి',
    'not_provided': 'ఇవ్వలేదు',
    'edit_profile': 'ప్రొఫైల్ సవరించండి',
    'upload_document': 'పత్రం అప్లోడ్ చేయండి',
    'view_notifications': 'అర్థిక అభ్యర్థనలు',
    'view_loan_history': 'లోన్ చరిత్రను చూడండి',
    'view_spending_patterns': 'ఖర్చు ప్యాటర్న్లను చూడండి',
    'app_settings': 'యాప్ సెట్టింగ్స్',
    'logout': 'లాగౌట్',
    'mark_all_as_read': 'అన్నింటినీ చదివినట్లు గుర్తించండి',
    'no_notifications': 'నోటిఫికేషన్లు లేవు',
    'unread': 'చదవనిది',
    'full_name': 'పూర్తి పేరు',
    'enter_full_name': 'మీ పూర్తి పేరును నమోదు చేయండి',
    'enter_email': 'మీ ఇమెయిల్ ను నమోదు చేయండి',
    'enter_phone_number': 'మీ ఫోన్ నంబర్ ను నమోదు చేయండి',
    'enter_address': 'మీ చిరునామాను నమోదు చేయండి',
    'enter_occupation': 'మీ వృత్తిని నమోదు చేయండి',
    'cancel': 'రద్దు చేయండి',
    'save_changes': 'మార్పులను సేవ్ చేయండి',
    'back': 'వెనుకకు',
    
    // Loan History Screen
    'loading_loan_history': 'లోన్ చరిత్ర లోడవుతోంది',
    'no_loan_history_found': 'లోన్ చరిత్ర కనుగొనబడలేదు',
    'disbursed': 'డిస్బర్స్ చేయబడింది',
    'repaid': 'తిరస్కరించబడింది',
    'repayment_due': 'చెల్లింపు గడువు',
    
    // Spending Patterns Screen
    'spending_patterns_title': 'ఖర్చు ప్యాటర్న్లు',
    'loading_spending_patterns': 'ఖర్చు ప్యాటర్న్లు లోడవుతోంది',
    'daily': 'రోజువారీ',
    'weekly': 'వారం వారం',
    'monthly': 'నెల వారం',
    'spending_by_category': 'వర్గం ప్రకారం ఖర్చు',
    'spending_summary': 'ఖర్చు సారాంశం',
    'groceries': 'కిరాణా వస్తువులు',
    'transport': 'రవాణా',
    'entertainment': 'వినోదం',
    'utilities': 'సౌకర్యాలు',
    'dining': 'భోజనం',
    'other': 'ఇతర',
    'rent': 'బాడి ఖర్చు',
    'user_diary': 'వినియోగదారు డయరీ',
    'add_financial_note': 'ఆర్థిక గమనిక లేదా కార్యాచరణను జోడించండి...',
    'add_entry': 'ఎంట్రీని జోడించండి',
    'delete': 'తొలగించు',
    'no_diary_entries': 'ఇప్పటివరకు డయరీ ఎంట్రీలు లేవు. మీ మొదటి ఆర్థిక గమనికను జోడించండి!',
    
    // Settings Screen
    'notifications': 'నోటిఫికేషన్లు',
    'enable_notifications': 'నోటిఫికేషన్లను ప్రారంభించండి',
    'email_notifications': 'ఇమెయిల్ నోటిఫికేషన్లు',
    'sms_notifications': 'SMS నోటిఫికేషన్లు',
    'appearance': 'కనిపించే విధం',
    'dark_mode': 'డార్క్ మోడ్',
    'view_mode': 'వీక్షణ మోడ్',
    'mobile_view': 'మొబైల్ వీక్షణ',
    'desktop_view': 'డెస్క్టాప్ వీక్షణ',
    'preferences': 'ప్రాధాన్యతలు',
    'language': 'భాష',
    'currency': 'కరెన్సీ',
    'english': 'ఆంగ్లం',
    'hindi': 'హిందీ',
    'tamil': 'తమిళం',
    'telugu': 'తెలుగు',
    'kannada': 'కన్నడ',
    'indian_rupee': 'భారతీయ రూపాయి (₹)',
    'us_dollar': 'US డాలర్ ($)',
    'euro': 'యూరో (€)',
    'reset_to_default': 'డిఫాల్ట్‌కు రీసెట్ చేయండి',
    'save_settings': 'సెట్టింగ్స్ సేవ్ చేయండి',
    'settings_saved_successfully': 'సెట్టింగ్స్ విజయవంతంగా సేవ్ చేయబడ్డాయి!',
    
    // Login/Signup Screen
    'login': 'లాగిన్',
    'signup': 'సైన్ అప్',
    'username': 'వినియోగదారు పేరు',
    'email_or_username': 'ఈమెయిల్ లేదా వినియోగదారు పేరు',
    'password': 'పాస్ వర్డ్',
    'confirm_password': 'పాస్ వర్డ్ ని నిర్ధారించండి',
    'passwords_do_not_match': 'పాస్ వర్డ్ లు సరిపోలడం లేదు',
    'dont_have_account': 'ఖాతా లేదా?',
    'already_have_account': 'ఇప్పటికే ఒక ఖాతా ఉందా?',
    
    // Notification System
    'just_now': 'ఇప్పుడే',
    'minutes_ago': '{minutes} నిమిషాల క్రితం',
    'hours_ago': '{hours} గంటల క్రితం',
    'days_ago': '{days} రోజుల క్రితం',
    'loan_approved': 'లోన్ ఆమోదించబడింది',
    'loan_application_approved': '₹{amount} కోసం మీ లోన్ అప్లికేషన్ ఆమోదించబడింది.',
    'payment_due': 'చెల్లింపు గడువు',
    'payment_due_message': '₹{amount} మీ లోన్ చెల్లింపు 3 రోజుల్లో గడువు తీరబోతోంది.',
    'payment_received': 'చెల్లింపు అందుకున్నారు',
    'payment_received_message': '₹{amount} మీ లోన్ చెల్లింపు మాకు అందుకుంది.',
    'loan_disbursed': 'లోన్ డిస్బర్స్ చేయబడింది',
    'loan_disbursed_message': '₹{amount} మీ లోన్ మీ ఖాతాకు డిస్బర్స్ చేయబడింది.',
    
    // Common terms
    'try_again': 'మళ్ళీ ప్రయత్నించండి',
    
    // Demo Users
    'rani': 'రాని',
    'amit': 'అమిత్',
    'priya': 'ప్రియ',
    'low_risk': 'తక్కువ ప్రమాదం',
    'medium_risk': 'మధ్యస్థ ప్రమాదం',
    'high_risk': 'అధిక ప్రమాదం',
    
    // Common terms
    'minutes': 'నిమిషాలు',
    'rupees': '₹',
  },
  kn: {
    // Onboarding Screen
    'justifi': 'ಜಸ್ಟಿಫಿ',
    'instant_micro_loans': 'ರಶೀದಿಗಳನ್ನು ಬಳಸಿಕೊಂಡು ತಕ್ಷಣ ಮೈಕ್ರೋ-ಲೋನ್ಗಳು',
    'get_approved': 'CIBIL ಅಥವಾ PAN ಇಲ್ಲದೆಯೇ ನಿಮಿಷಗಳಲ್ಲಿ ಅನುಮೋದನೆ ಪಡೆಯಿರಿ',
    'decision_time': '5 ನಿಮಿಷಗಳಲ್ಲಿ ನಿರ್ಧಾರ',
    'no_pan_required': 'PAN/ಆಧಾರ್ ಅಗತ್ಯವಿಲ್ಲ',
    'loan_amount': '₹10,000 ವರೆಗೆ ಲೋನ್ಗಳು',
    'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
    'terms_consent': 'ಮುಂದುವರಿದರೆ, ನೀವು ನಮ್ಮ ಸೇವಾ ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿಗೆ ಸಮ್ಮತಿಸುತ್ತೀರಿ',
    
    // Upload Screen
    'upload_documents': 'ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    'upload_salary_receipt': 'ನಿಮ್ಮ ಸಂಬಳ ರಶೀದಿಯನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    'upload_salary_receipt_description': 'ನಿಮ್ಮ ಕ್ರೆಡಿಟ್ ಸ್ಕೋರ್ ಲೆಕ್ಕಹಾಕಲು ನಿಮ್ಮ ಸಂಬಳ ರಶೀದಿಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
    'upload_bank_statement': 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಹೇಳಿಕೆಯನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    'upload_bank_statement_description': 'ನಿಮ್ಮ ಕ್ರೆಡಿಟ್ ಸ್ಕೋರ್ ಲೆಕ್ಕಹಾಕಲು ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಹೇಳಿಕೆಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
    'choose_salary_receipt': 'ಸಂಬಳ ರಶೀದಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'choose_bank_statement': 'ಬ್ಯಾಂಕ್ ಹೇಳಿಕೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'upload_salary_receipt_button': 'ಸಂಬಳ ರಶೀದಿಯನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    'upload_bank_statement_button': 'ಬ್ಯಾಂಕ್ ಹೇಳಿಕೆಯನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    'salary_receipt_uploaded_successfully': 'ಸಂಬಳ ರಶೀದಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಅಪ್ಲೋಡ್ ಮಾಡಲಾಗಿದೆ!',
    'bank_statement_uploaded_successfully': 'ಬ್ಯಾಂಕ್ ಹೇಳಿಕೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಅಪ್ಲೋಡ್ ಮಾಡಲಾಗಿದೆ!',
    'please_upload_at_least_one_document': 'ದಯವಿಟ್ಟು ಕನಿಷ್ಠ ಒಂದು ದಾಖಲೆಯನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    'drag_drop_receipts': 'ನಿಮ್ಮ ರಶೀದಿ ಫೈಲ್ಗಳನ್ನು ಇಲ್ಲಿಗೆ ಎಳೆದು ಬಿಡಿ',
    'or': 'ಅಥವಾ',
    'choose_files': 'ಫೈಲ್ಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'selected': 'ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ',
    'or_try_demo': 'ಅಥವಾ ಡೆಮೋ ಡೇಟಾದೊಂದಿಗೆ ಪ್ರಯತ್ನಿಸಿ:',
    'use_demo_data': 'ಡೆಮೋ ಡೇಟಾವನ್ನು ಬಳಸಿ',
    'processing': 'ಪ್ರಕ್ರಿಯಿಸಲಾಗುತ್ತಿದೆ...',
    'calculate_my_score': 'ನನ್ನ ಸ್ಕೋರ್ ಅನ್ನು ಲೆಕ್ಕಹಾಕಿ',
    'no_pan_aadhaar_required': 'PAN/ಆಧಾರ್ ಅಗತ್ಯವಿಲ್ಲ. ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಎನ್ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ ಮತ್ತು ಸುರಕ್ಷಿತವಾಗಿದೆ.',
    'please_select_file': 'ದಯವಿಟ್ಟು ಮೊದಲು ಒಂದು ಫೈಲ್ ಅನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'error_processing_request': 'ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಪ್ರಕ್ರಿಯಿಸುವಾಗ ದೋಷ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'please_select_demo_user': 'ದಯವಿಟ್ಟು ಒಬ್ಬ ಡೆಮೋ ಬಳಕೆದಾರನನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    
    // Result Screen
    'your_credit_assessment': 'ನಿಮ್ಮ ಕ್ರೆಡಿಟ್ ಮೌಲ್ಯಾಂಕನ',
    'trust_score': 'ಟ್ರಸ್ಟ್ಸ್ಕೋರ್',
    'top_reasons': 'ಅತ್ಯುತ್ತಮ ಕಾರಣಗಳು',
    'loan_offer': 'ಲೋನ್ ಆಫರ್',
    'available_for_disbursement': 'ತಕ್ಷಣ ಡಿಸ್ಬರ್ಸ್ಮೆಂಟ್ಗಾಗಿ ಲಭ್ಯವಿದೆ',
    'accept_loan': 'ಲೋನ್ ಅನ್ನು ಸ್ವೀಕರಿಸಿ',
    'loan_disbursed_success': '₹{amount} ಲೋನ್ ಅನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಡಿಸ್ಬರ್ಸ್ ಮಾಡಲಾಗಿದೆ!',
    'failed_to_disburse_loan': 'ಲೋನ್ ಡಿಸ್ಬರ್ಸ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ',
    'loan_approved': 'ಲೋನ್ ಅನುಮೋದಿಸಲಾಗಿದೆ!',
    'error': 'ದೋಷ',
    'transaction_id': 'ವ್ಯವಹಾರ ಐಡಿ',
    'amount': 'ಮೊತ್ತ',
    'view_profile': 'ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ',
    'loan_history': 'ಲೋನ್ ಇತಿಹಾಸ',
    'spending_patterns': 'ಖರ್ಚು ವಿಧಾನಗಳು',
    'settings': 'ಸೆಟ್ಟಿಂಗ್ಗಳು',
    'assess_another_person': 'ಮತ್ತೊಬ್ಬರನ್ನು ಮೌಲ್ಯಾಂಕನ ಮಾಡಿ',
    'data_protected': 'ನಿಮ್ಮ ಡೇಟಾವನ್ನು ರಕ್ಷಿಸಲಾಗಿದೆ. ನಾವು ಅದನ್ನು ಕ್ರೆಡಿಟ್ ಮೌಲ್ಯಾಂಕನಕ್ಕಾಗಿ ಮಾತ್ರ ಬಳಸುತ್ತೇವೆ.',
    'approved': 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
    'approved_with_cap': 'ಕ್ಯಾಪ್ ಜೊತೆ ಅನುಮೋದಿಸಲಾಗಿದೆ',
    'under_review': 'ಪರಿಶೀಲನೆಯಲ್ಲಿ',
    'rejected': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    'pending': 'ಬಾಕಿ ಇದೆ',
    'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ',
    'hundred': '100',
    
    // Profile Screen
    'user_profile': 'ಬಳಕೆದಾರ ಪ್ರೊಫೈಲ್',
    'user': 'ಬಳಕೆದಾರ',
    'user_initial': 'ಬ',
    'email': 'ಇಮೇಲ್',
    'phone': 'ಫೋನ್',
    'address': 'ವಿಳಾಸ',
    'occupation': 'ವೃತ್ತಿ',
    'not_provided': 'ನೀಡಲಾಗಿಲ್ಲ',
    'edit_profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    'upload_document': 'ದಾಖಲೆಯನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    'view_notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'view_loan_history': 'ಲೋನ್ ಇತಿಹಾಸವನ್ನು ವೀಕ್ಷಿಸಿ',
    'view_spending_patterns': 'ಖರ್ಚು ವಿಧಾನಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'app_settings': 'ಆಪ್ ಸೆಟ್ಟಿಂಗ್ಗಳು',
    'logout': 'ಲಾಗ್ ಔಟ್',
    'mark_all_as_read': 'ಎಲ್ಲವನ್ನು ಓದಿದಂತೆ ಗುರುತಿಸಿ',
    'no_notifications': 'ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    'unread': 'ಓದದೆ ಇರುವ',
    'full_name': 'ಪೂರ್ಣ ಹೆಸರು',
    'enter_full_name': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    'enter_email': 'ನಿಮ್ಮ ಇಮೇಲ್ ಅನ್ನು ನಮೂದಿಸಿ',
    'enter_phone_number': 'ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    'enter_address': 'ನಿಮ್ಮ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ',
    'enter_occupation': 'ನಿಮ್ಮ ವೃತ್ತಿಯನ್ನು ನಮೂದಿಸಿ',
    'cancel': 'ರದ್ದುಮಾಡಿ',
    'save_changes': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    'back': 'ಹಿಂದಕ್ಕೆ',
    'notifications_feature_coming_soon': 'ಅಧಿಸೂಚನೆಗಳು ವೈಶಿಷ್ಟ್ಯವು ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತದೆ!',
    
    // Loan History Screen
    'loading_loan_history': 'ಲೋನ್ ಇತಿಹಾಸವನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ',
    'no_loan_history_found': 'ಯಾವುದೇ ಲೋನ್ ಇತಿಹಾಸ ಕಂಡುಬಂದಿಲ್ಲ',
    'disbursed': 'ಡಿಸ್ಬರ್ಸ್ ಮಾಡಲಾಗಿದೆ',
    'repaid': 'ಮರುಪಾವತಿ ಮಾಡಲಾಗಿದೆ',
    'repayment_due': 'ಮರುಪಾವತಿ ಗಡುವು',
    
    // Spending Patterns Screen
    'spending_patterns_title': 'ಖರ್ಚು ವಿಧಾನಗಳು',
    'loading_spending_patterns': 'ಖರ್ಚು ವಿಧಾನಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ',
    'daily': 'ದೈನಿಕ',
    'weekly': 'ಸಾಪ್ತಾಹಿಕ',
    'monthly': 'ಮಾಸಿಕ',
    'spending_by_category': 'ವರ್ಗದ ಪ್ರಕಾರ ಖರ್ಚು',
    'spending_summary': 'ಖರ್ಚು ಸಾರಾಂಶ',
    'groceries': 'ಅಂಗಡಿ ಸರಕುಗಳು',
    'transport': 'ಸಾರಿಗೆ',
    'entertainment': 'ಮನರಂಜನೆ',
    'utilities': 'ಸೌಲಭ್ಯಗಳು',
    'dining': 'ಊಟ',
    'other': 'ಇತರೆ',
    'rent': 'ಬಾಡಿಗೆ',
    'user_diary': 'ಬಳಕೆದಾರ ಡೈರಿ',
    'add_financial_note': 'ಹಣಕಾಸು ಟಿಪ್ಪಣಿ ಅಥವಾ ಚಟುವಟಿಕೆಯನ್ನು ಸೇರಿಸಿ...',
    'add_entry': 'ನಮೂದನ್ನು ಸೇರಿಸಿ',
    'delete': 'ಅಳಿಸಿ',
    'no_diary_entries': 'ಇನ್ನೂ ಡೈರಿ ನಮೂದುಗಳಿಲ್ಲ. ನಿಮ್ಮ ಮೊದಲ ಹಣಕಾಸು ಟಿಪ್ಪಣಿಯನ್ನು ಸೇರಿಸಿ!',
    
    // Settings Screen
    'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'enable_notifications': 'ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'email_notifications': 'ಇಮೇಲ್ ಅಧಿಸೂಚನೆಗಳು',
    'sms_notifications': 'SMS ಅಧಿಸೂಚನೆಗಳು',
    'appearance': 'ನೋಟ',
    'dark_mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
    'view_mode': 'ವೀಕ್ಷಣಾ ಮೋಡ್',
    'mobile_view': 'ಮೊಬೈಲ್ ವೀಕ್ಷಣೆ',
    'desktop_view': 'ಡೆಸ್ಕ್ಟಾಪ್ ವೀಕ್ಷಣೆ',
    'preferences': 'ಆದ್ಯತೆಗಳು',
    'language': 'ಭಾಷೆ',
    'currency': 'ಕರೆನ್ಸಿ',
    'english': 'ಇಂಗ್ಲಿಷ್',
    'hindi': 'ಹಿಂದಿ',
    'tamil': 'ತಮಿಳು',
    'telugu': 'ತೆಲುಗು',
    'kannada': 'ಕನ್ನಡ',
    'indian_rupee': 'ಭಾರತೀಯ ರೂಪಾಯಿ (₹)',
    'us_dollar': 'US ಡಾಲರ್ ($)',
    'euro': 'ಯೂರೋ (€)',
    'reset_to_default': 'ಡೀಫಾಲ್ಟ್ಗೆ ಮರುಹೊಂದಿಸಿ',
    'save_settings': 'ಸೆಟ್ಟಿಂಗ್ಗಳನ್ನು ಉಳಿಸಿ',
    'settings_saved_successfully': 'ಸೆಟ್ಟಿಂಗ್ಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!',
    
    // Login/Signup Screen
    'login': 'ಲಾಗಿನ್',
    'signup': 'ಸೈನ್ ಅಪ್',
    'username': 'ಬಳಕೆದಾರಹೆಸರು',
    'email_or_username': 'ಇಮೇಲ್ ಅಥವಾ ಬಳಕೆದಾರಹೆಸರು',
    'password': 'ಪಾಸ್ ವರ್ಡ್',
    'confirm_password': 'ಪಾಸ್ ವರ್ಡ್ ಅನ್ನು ದೃ .ಿಕೊಳ್ಳಿ',
    'passwords_do_not_match': 'ಪಾಸ್ ವರ್ಡ್ ಗಳು ಹೊಂದಾಣಿಕೆಯಾಗುವುದಿಲ್ಲ',
    'dont_have_account': 'ಖಾತೆ ಇಲ್ಲವೇ?',
    'already_have_account': 'ಈಗಾಗಲೇ ಒಂದು ಖಾತೆ ಇದೆಯೇ?',
    
    // Notification System
    'just_now': 'ಈಗಷ್ಟೇ',
    'minutes_ago': '{minutes} ನಿಮಿಷಗಳ ಹಿಂದೆ',
    'hours_ago': '{hours} ಗಂಟೆಗಳ ಹಿಂದೆ',
    'days_ago': '{days} ದಿನಗಳ ಹಿಂದೆ',
    'loan_approved': 'ಲೋನ್ ಅನುಮೋದಿಸಲಾಗಿದೆ',
    'loan_application_approved': '₹{amount} ಗಾಗಿ ನಿಮ್ಮ ಲೋನ್ ಅರ್ಜಿಯನ್ನು ಅನುಮೋದಿಸಲಾಗಿದೆ.',
    'payment_due': 'ಪಾವತಿ ಗಡುವು',
    'payment_due_message': '₹{amount} ನಿಮ್ಮ ಲೋನ್ ಪಾವತಿ 3 ದಿನಗಳಲ್ಲಿ ಗಡುವು ತೀರುತ್ತದೆ.',
    'payment_received': 'ಪಾವತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    'payment_received_message': '₹{amount} ನಿಮ್ಮ ಲೋನ್ ಪಾವತಿಯನ್ನು ನಾವು ಸ್ವೀಕರಿಸಿದ್ದೇವೆ.',
    'loan_disbursed': 'ಲೋನ್ ಡಿಸ್ಬರ್ಸ್ ಮಾಡಲಾಗಿದೆ',
    'loan_disbursed_message': '₹{amount} ನಿಮ್ಮ ಲೋನ್ ಅನ್ನು ನಿಮ್ಮ ಖಾತೆಗೆ ಡಿಸ್ಬರ್ಸ್ ಮಾಡಲಾಗಿದೆ.',
    
    // Common terms
    'try_again': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    
    // Demo Users
    'rani': 'ರಾನಿ',
    'amit': 'ಅಮಿತ್',
    'priya': 'ಪ್ರಿಯಾ',
    'low_risk': 'ಕಡಿಮೆ ಅಪಾಯ',
    'medium_risk': 'ಮಧ್ಯಮ ಅಪಾಯ',
    'high_risk': 'ಅಧಿಕ ಅಪಾಯ',
    
    // Common terms
    'minutes': 'ನಿಮಿಷಗಳು',
    'rupees': '₹',
  }
};

// Function to get translated text
export const t = (key, language = 'en') => {
  return translations[language]?.[key] || translations['en']?.[key] || key;
};
